var song = [
	{id : 927, name : "Francium", credit : "チータン feat. 初音ミク", reading : "ふらんしうむ"},
	{id : 906, name : "Booo!", credit : "TOKOTOKO(西沢さんP) feat. 音街ウナ", reading : "ぶー"},
	{id : 394, name : "甲賀忍法帖", credit : "陰陽座", reading : "こうがにんぽうちょう"},
	{id : 689, name : "together", credit : "あきよしふみえ", reading : "とぅげゃざー"},
	{id : 899, name : "ファンサ", credit : "HoneyWorks feat. mona (CV: 夏川椎菜)", reading : "ふぁんさ"},
	{id : 359, name : "紅蓮華", credit : "LiSA", reading : "ぐれんげ"},
	{id : 621, name : "ただ君に晴れ", credit : "ヨルシカ", reading : "ただきみにはれ"},
	{id : 408, name : "God knows...", credit : "平野綾", reading : "ごっどのーず"},
	{id : 945, name : "ふわふわ時間", credit : "放課後ティータイム", reading : "ふわふわたいむ"},
	{id : 568, name : "星間飛行", credit : "中島愛", reading : "せいかんひこう"},
	{id : 744, name : "名前のない怪物", credit : "EGOIST", reading : "なまえのないかいぶつ"},
	{id : 1020, name : "三日月", credit : "絢香", reading : "みかづき"},
	{id : 230, name : "オレンジ", credit : "逢坂大河(釘宮理恵) 櫛枝実乃梨(堀江由衣) 川嶋亜美(喜多村英梨)", reading : "おれんじ"},
	{id : 629, name : "魂のルフラン", credit : "高橋洋子", reading : "たましいのるふらん"},
	{id : 176, name : "Exterminate", credit : "水樹奈々", reading : "えくすたーみねいと"},
	{id : 413, name : "コネクト", credit : "ClariS", reading : "こねくと まどまぎ まどマギ"},
	{id : 319, name : "Catch you Catch me", credit : "丹下桜", reading : "きゃっちゆーきゃっちみー"},
	{id : 366, name : "檄!帝国華撃団", credit : "帝国歌劇団、横山智佐", reading : "げきていこくかげきだん"},
	{id : 923, name : "白金ディスコ", credit : "井口裕香", reading : "ぷらちなでぃすこ"},
	{id : 1124, name : "ライオン", credit : "May'n、中島愛", reading : "らいおん"},
	{id : 591, name : "全力バタンキュー", credit : "A応P", reading : "ぜんりょくばたんきゅー"},
	{id : 369, name : "月光花", credit : "Janne Da Arc", reading : "げっこうか"},
	{id : 228, name : "オリオンをなぞる", credit : "UNISON SQUARE GARDEN", reading : "おりおんをなぞる"},
	{id : 233, name : "ガーネット", credit : "奥華子", reading : "がーねっと"},
	{id : 1035, name : "ムーンライト伝説", credit : "DALI", reading : "むーんらいとでんせつ"},
	{id : 671, name : "TESTAMENT", credit : "水樹奈々", reading : "てすためんと"},
	{id : 723, name : "Don't say \"lazy\"", credit : "放課後ティータイム", reading : "どんとせいれいじー"},
	{id : 231, name : "オレンジ ", credit : "7!!", reading : "おれんじ "},
	{id : 186, name : "Everything", credit : "MISIA", reading : "えぶりしんぐ"},
	{id : 205, name : "おジャ魔女カーニバル!!", credit : "MAHO堂", reading : "おじゃまじょかーにばる"},
	{id : 718, name : "トリセツ", credit : "西野カナ", reading : "とりせつ"},
	{id : 469, name : "secret base ~君がくれたもの~", credit : "ZONE", reading : "しーくれっとべーすきみがくれたもの"},
	{id : 438, name : "さくらんぼ", credit : "大塚愛", reading : "さくらんぼ"},
	{id : 771, name : "ノーダウト", credit : "Official髭男dism", reading : "のーだうと"},
	{id : 596, name : "そばかす", credit : "JUDY AND MARY", reading : "そばかす"},
	{id : 139, name : "ウィーアー！", credit : "きただにひろし", reading : "うぃーあー we are"},
	{id : 297, name : "気まぐれロマンティック", credit : "いきものがかり", reading : "きまぐれろまんてぃっく"},
	{id : 497, name : "シュガーソングとビターステップ", credit : "Unison Square Garden", reading : "しゅがーそんぐとびたーすてっぷ"},
	{id : 1046, name : "めざせポケモンマスター", credit : "松本梨香", reading : "めざせぽけもんますたー"},
	{id : 789, name : "Butter-Fly", credit : "和田光司", reading : "ばたふらい "},
	{id : 155, name : "うっせぇわ", credit : "Ado", reading : "うっせぇわ"},
	{id : 830, name : "ハム太郎とっとこうた", credit : "ハムちゃんず", reading : "はむたろうとっとこうた"},
	{id : 1134, name : "ラピスラズリ", credit : "藍井エイル", reading : "らぴすらずり"},
	{id : 625, name : "たばこ", credit : "コレサワ", reading : "たばこ"},
	{id : 933, name : "ブルーバード", credit : "いきものがかり", reading : "ぶるーばーど"},
	{id : 764, name : "猫", credit : "DISH//", reading : "ねこ"},
	{id : 728, name : "NAO", credit : "HY", reading : "なお"},
	{id : 107, name : "生きてこそ", credit : "Kiroro", reading : "いきてこそ"},
	{id : 481, name : "自分REST@RT", credit : "天海春香(中村繪里子),星井美希(長谷川明子),如月千早(今井麻美),高槻やよい(仁後真耶子),萩原雪歩(長谷優里奈),菊地真(平田宏美),双海真美(下田麻美),四条貴音(原由実),我那覇響(沼倉愛美)", reading : "じぶんりすたーと"},
	{id : 73, name : "ANIMA", credit : "ReoNa", reading : "あにま"},
	{id : 366, name : "檄！帝国華撃団", credit : "帝国歌劇団、横山智佐", reading : "げきていこくかげきだん"},
	{id : 523, name : "心臓を捧げよ！", credit : "LinkedHorizon", reading : "しんぞうをささげよ"},
	{id : 277, name : "カロン", credit : "ねごと", reading : "かろん"},
	{id : 759, name : "ねぇ", credit : "藤田麻衣子", reading : "ねぇ"},
	{id : 505, name : "憧憬と屍の道", credit : "Linked Horizon", reading : "しょうけいとしかばねのみち"},
	{id : 943, name : "プロローグ", credit : "Uru", reading : "ぷろろーぐ"},
	{id : 368, name : "月光", credit : "鬼束ちひろ", reading : "げっこう"},
	{id : 652, name : "蝶々結び", credit : "Aimer", reading : "ちょうちょうむすび"},
	{id : 1184, name : "恋愛サーキュレーション", credit : "千石撫子(花澤香菜)", reading : "れんあいさーきゅれーしょん 物語シリーズ"},
	{id : 241, name : "かくしん的☆めたまるふぉ〜ぜっ！", credit : "土間うまる（田中あいみ）", reading : "かくしんてきめためるふぉーぜ"},
	{id : 941, name : "ふ·れ·ん·ど·し·た·い", credit : "学園生活部", reading : "ふれんどしたい"},
	{id : 615, name : "太陽曰く燃えよカオス", credit : "後ろから這いより隊G", reading : "たいよういわくもえよかおす"},
	{id : 132, name : "インドア系ならトラックメイカー", credit : "Yunomi、nicamoq", reading : "いんどあけいならどらっくめいかー"},
	{id : 1110, name : "ようこそジャパリパークへ", credit : "どうぶつビスケッツ", reading : "ようこそじゃぱりぱーくへ"},
	{id : 142, name : "ヴィーナスとジーザス", credit : "やくしまるえつこ", reading : "ヴぃーなすとじーざす"},
	{id : 388, name : "恋は渾沌の隷也", credit : "後ろから這いより隊G", reading : "こいはかおすのしもべなり"},
	{id : 548, name : "START:DASH!!", credit : "μ's", reading : "すたーとだっしゅ"},
	{id : 592, name : "創聖のアクエリオン", credit : "AKINO", reading : "そうせいこあくえりおん"},
	{id : 1119, name : "夜に駆ける", credit : "YOASOBI", reading : "よるにかける"},
	{id : 623, name : "タッチ", credit : "岩崎良美", reading : "たっち"},
	{id : 855, name : "ピースサイン", credit : "米津玄師", reading : "ぴーすさいん"},
	{id : 645, name : "CHE.R.RY", credit : "yui", reading : "ちぇりー  cherry"},
	{id : 1105, name : "夢をかなえてドラえもん", credit : "Mao", reading : "ゆめをかなえてどらえもん"},
	{id : 569, name : "青春アミーゴ", credit : "修二と彰", reading : "せいしゅんあみーご"},
	{id : 426, name : "サイレントマジョリティー", credit : "櫻坂46", reading : "さいれんとまじょりてぃー"},
	{id : 482, name : "Shine!!", credit : "CINDERELLA PROJECT", reading : "しゃーいん"},
	{id : 319, name : "Catch You Catch Me", credit : "丹下桜", reading : "きゃっちゆーきゃっちみー"},
	{id : 599, name : "空色デイズ", credit : "中川翔子", reading : "そらいろでいず"},
	{id : 966, name : "僕らの戦場", credit : "ワルキューレ", reading : "ぼくらのせんじょう"},
	{id : 242, name : "輝夜の城で踊りたい", credit : "μ's", reading : "かぐやのしろでおどりたい"},
	{id : 964, name : "ぼくのしーくれっと", credit : "犬山たまき", reading : "ぼくのしーくれっと"},
	{id : 1073, name : "やさしいキスをして", credit : "DREAMS COME TRUE", reading : "やさしいきすをして"},
	{id : 67, name : "貴方解剖純愛歌〜死ね〜", credit : "あいみょん", reading : "あなたかいぼうじゅんあいかしね"},
	{id : 361, name : "黒毛和牛上塩タン焼680円", credit : "大塚愛", reading : "くろげわぎゅうじょうしおタンやきろっぴゃくはちじゅうえん"},
	{id : 80, name : "天城越え", credit : "石川 さゆり", reading : "あまぎごえ"},
	{id : 293, name : "ギブス", credit : "椎名林檎", reading : "ぎぶす"},
	{id : 1054, name : "メリクリ", credit : "BoA", reading : "めりくり"},
	{id : 19, name : "逢いたくていま", credit : "MISIA", reading : "あいたくていま"},
	{id : 45, name : "赤いスイートピー", credit : "松田聖子", reading : "あかいすいーとぴー"},
	{id : 579, name : "世界は恋に落ちている", credit : "CHICO with HoneyWorks", reading : "せかいはこいにおちている"},
	{id : 1152, name : "ラムのラブソング", credit : "松谷祐子", reading : "らむのらぶそんぐ"},
	{id : 526, name : "シンデレラガール", credit : "King & Prince", reading : "しんでれらがーる"},
	{id : 376, name : "恋", credit : "星野源", reading : "こい"},
	{id : 248, name : "風になる", credit : "つじあやの", reading : "かぜになる"},
	{id : 884, name : "秘密の扉から会いにきて", credit : "田村ゆかり", reading : "ひみつのとびらからあいにきて"},
	{id : 871, name : "ヒトリゴト", credit : "ClariS", reading : "ひとりごと"},
	{id : 1065, name : "motto☆派手にね!", credit : "戸松遥", reading : "もっとはでにね"},
	{id : 458, name : "残酷な天使のテーゼ", credit : "高橋洋子", reading : "ざんこくなてんしのてーぜ"},
	{id : 64, name : "あたしを彼女にしたいなら", credit : "コレサワ", reading : "あたしをかのじょにしたいなら"},
	{id : 844, name : "春よ、来い", credit : "松任谷由実", reading : "はるよこい"},
	{id : 707, name : "となりのトトロ", credit : "井上あずみ", reading : "となりのととろ"},
	{id : 519, name : "深愛", credit : "水樹奈々", reading : "しんあい"},
	{id : 689, name : "Together", credit : "あきよしふみえ", reading : "とぅげゃざー"},
	{id : 861, name : "光るなら", credit : "Goose house", reading : "ひかるなら"},
	{id : 195, name : "オーケストラ", credit : "BiSH", reading : "おーけすとら"},
	{id : 1096, name : "UNION", credit : "OxT", reading : "ゆにおん"},
	{id : 325, name : "Q&A リサイタル!", credit : "戸松遥", reading : "きゅーあんどえーりさいたる"},
	{id : 987, name : "本日、満開ワタシ色!", credit : "伊藤静、矢作紗友里、中尾衣里、浅野真澄", reading : "ほんじつまんかいわたしいろ"},
	{id : 435, name : "桜のあと", credit : "UNISON SQUARE GARDEN", reading : "さくらのあと"},
	{id : 484, name : "じゃじゃ馬にさせないで", credit : "西尾悦子", reading : "じゃじゃうまにさせないで"},
	{id : 800, name : "ハッピー・ジャムジャム", credit : "M・S・J", reading : "はっぴーじゃむじゃむ"},
	{id : 824, name : "Honey Come!!", credit : "小倉唯", reading : "はにーかむ"},
	{id : 818, name : "花ハ踊レヤいろはにほ", credit : "チーム\"ハナヤマタ\"", reading : "はなはおどれやいろはにほ"},
	{id : 986, name : "本能", credit : "椎名林檎", reading : "ほんおう"},
	{id : 30, name : "I LOVE YOU", credit : "尾崎豐", reading : "あいらぶゆー"},
	{id : 349, name : "GLAMOROUS SKY", credit : "中島美嘉", reading : "ぐらまらすすかい"},
	{id : 693, name : "Tomorrow never knows", credit : "Mr.Children", reading : "とぅもろーねヴぁーのーず"},
	{id : 699, name : "時の流れに身をまかせ", credit : "テレサ・テン", reading : "ときのながれにみをまかせ"},
	{id : 265, name : "カブトムシ", credit : "Aiko", reading : "かぶとむし"},
	{id : 1177, name : "Rainy Blue", credit : "德永英明", reading : "れいにーぶるー レイニーブルー"},
	{id : 121, name : "糸", credit : "中島みゆき", reading : "いと"},
	{id : 822, name : "ハナミズキ", credit : "一青窈", reading : "はなみずき"},
	{id : 890, name : "秒針を噛む", credit : "ずっと真夜中でいいのに。", reading : "びょうしんをかむ"},
	{id : 996, name : "マジックナンバー", credit : "坂本真綾", reading : "まじっくなんばー"},
	{id : 236, name : "怪物", credit : "YOASOBI", reading : "かいぶつ"},
	{id : 1193, name : "Lost my music", credit : "平野綾", reading : "ろすとまいみゅーじっく"},
	{id : 495, name : "17才", credit : "ハルカトミユキ", reading : "じゅうななさい"},
	{id : 99, name : "インフェルノ", credit : "Mrs. GREEN APPLE", reading : "あんふぇるの"},
	{id : 622, name : "ダダダダ天使", credit : "ナナヲアカリ", reading : "だだだだてんし"},
	{id : 452, name : "さよならメモリーズ", credit : "supercell", reading : "さよならめもりーず"},
	{id : 311, name : "君の知らない物語", credit : "supercell", reading : "きみのしらないものがたり 物語シリーズ"},
	{id : 576, name : "世界に一つだけの花", credit : "SMAP", reading : "せかいにひとつだけのはな"},
	{id : 560, name : "Story", credit : "AI", reading : "すとーりー"},
	{id : 26, name : "I believe", credit : "絢香", reading : "あいびりーぶ"},
	{id : 942, name : "プロミスザスター", credit : "BiSH", reading : "ぷろみすざすたー"},
	{id : 1055, name : "メリッサ", credit : "ポルノグラフィティ", reading : "めりっさ"},
	{id : 922, name : "プラチナ", credit : "坂本真綾", reading : "ぷらちな"},
	{id : 408, name : "God Knows...", credit : "平野綾", reading : "ごっどのーず"},
	{id : 816, name : "花の唄", credit : "Aimer", reading : "はなのうた"},
	{id : 516, name : "シルエット", credit : "KANA-BOON", reading : "しるえっと"},
	{id : 24, name : "アイのシナリオ", credit : "CHiCO with HoneyWorks", reading : "あいのしなりお"},
	{id : 711, name : "友よ 〜 この先もずっと…", credit : "ケツメイシ", reading : "ともよこのさきもずっと"},
	{id : 264, name : "歌舞伎町の女王", credit : "椎名林檎", reading : "かぶきちょうのじょおう"},
	{id : 722, name : "曇天", credit : "DOES", reading : "どんてん"},
	{id : 501, name : "純潔パラドックス", credit : "水樹奈々", reading : "じゅんけつぱらどっくす"},
	{id : 1066, name : "モノクロのキス", credit : "シド", reading : "ものくろのきす"},
	{id : 445, name : "サムライハート", credit : "SPYAIR", reading : "さむらいはーと"},
	{id : 1166, name : "LOSER", credit : "米津玄師", reading : "るーさー"},
	{id : 246, name : "カサブタ", credit : "千綿ヒデノリ", reading : "かさぶた"},
	{id : 1006, name : "真赤な誓い", credit : "福山芳樹", reading : "まっかなちかい"},
	{id : 387, name : "恋はア・ラ・モード", credit : "東京ミュウミュウ", reading : "こいはあらもーど"},
	{id : 212, name : "乙女のポリシー", credit : "石田燿子", reading : "おとめのぽりしー"},
	{id : 959, name : "撲殺天使ドクロちゃん", credit : "石田燿子", reading : "ぼくさつてんしどくろちゃん"},
	{id : 1210, name : "私がオバさんになっても", credit : "森高千里", reading : "わたしがおばさんになっても"},
	{id : 825, name : "バニラソルト", credit : "堀江由衣", reading : "ばにらそると"},
	{id : 889, name : "ぴゅあぴゅあはーと", credit : "放課後ティータイム", reading : "ぴゅあぴゅあはーと"},
	{id : 199, name : "Over Soul", credit : "林原めぐみ", reading : "おーばーそーる"},
	{id : 170, name : "エージェント夜を往く", credit : "菊地真(CV: 平田宏美)", reading : "えーじぇんとはよるをゆく"},
	{id : 318, name : "Catch the Moment", credit : "LiSA", reading : "きゃっちざもーめんと"},
	{id : 930, name : "Pretender", credit : "Official髭男dism", reading : "ぷりてんだー"},
	{id : 581, name : "絶対零度θノヴァティック", credit : "ワルキューレ", reading : "ぜったいれいどのヴぁてぃっく"},
	{id : 134, name : "インフィニティ", credit : "シェリル・ノーム,ランカ・リー", reading : "いんふぃにてぃ"},
	{id : 910, name : "不確定性☆COSMIC MOVEMENT", credit : "ワルキューレ", reading : "ふかくていせいこすみっくむーヴめんと"},
	{id : 50, name : "AXIA〜ダイスキでダイキライ〜", credit : "カナメΔ安野希世乃、レイナΔ東山奈央、マキナΔ西田望見", reading : "あくしあだいすきでだいきらい"},
	{id : 955, name : "放課後オーバーフロウ", credit : "ランカ・リー(中島愛)", reading : "ほうかごおーばーふろう"},
	{id : 831, name : "破滅の純情", credit : "ワルキューレ", reading : "はめつのじゅんじょう"},
	{id : 120, name : "射手座☆午後九時Don't be late", credit : "シェリル・ノーム(May'n)", reading : "いてざごごくじどんとびーれいと"},
	{id : 7, name : "愛・おぼえていますか", credit : "ランカ・リー(中島愛)", reading : "あいおぼえていますか"},
	{id : 848, name : "ハレ晴レユカイ", credit : "平野綾、茅原実里、後藤 邑子", reading : "はれはれゆかい"},
	{id : 372, name : "限界突破×サバイバー", credit : "氷川きよし", reading : "げんかいとっぱさばいばー"},
	{id : 935, name : "Pray", credit : "川瀬智子", reading : "ぷれい"},
	{id : 88, name : "嵐の中で輝いて", credit : "米倉千尋", reading : "あらしのなかでかがやいて"},
	{id : 770, name : "Northern Lights", credit : "林原めぐみ", reading : "のーざんらいつ"},
	{id : 987, name : "本日、満開ワタシ色！", credit : "伊藤静、矢作紗友里、中尾衣里、浅野真澄", reading : "ほんじつまんかいわたしいろ"},
	{id : 780, name : "ハイティーン・ブギ", credit : "近藤真彦", reading : "はいてぃーんぶぎ"},
	{id : 1090, name : "UFO", credit : "ピンク・レディー", reading : "ゆーふぉ"},
	{id : 320, name : "CAT’S EYE", credit : "杏里", reading : "きゃっつあい"},
	{id : 680, name : "天使のウィンク", credit : "松田聖子", reading : "てんしのうぃんく"},
	{id : 178, name : "S・O・S", credit : "ピンク・レディー", reading : "えすおーえす"},
	{id : 940, name : "フレンズ", credit : "レベッカ", reading : "ふれんず"},
	{id : 837, name : "春一番", credit : "キャンディーズ", reading : "はるいちばん"},
	{id : 1173, name : "琉璃色の地球", credit : "松田聖子", reading : "るりいろのちきゅう"},
	{id : 224, name : "想い出がいっぱい", credit : "H2O", reading : "おもいでがいっぱい"},
	{id : 756, name : "にんげんっていいな", credit : "ガガガSP", reading : "にんげんっていいな"},
	{id : 446, name : "SOMEONE ELSE", credit : "種島ぽぷら,伊波まひる,轟八千代", reading : "さむわんえるず"},
	{id : 420, name : "さぁ", credit : "SURFACE", reading : "さぁ"},
	{id : 235, name : "廻廻奇譚", credit : "Eve", reading : "かいかいきだん"},
	{id : 42, name : "青空のナミダ", credit : "高橋瞳", reading : "あおぞらのなみだ"},
	{id : 814, name : "花に亡霊", credit : "ヨルシカ", reading : "はなにぼうれい"},
	{id : 1059, name : "もういちど ルミナス", credit : "Pastel*Palettes", reading : "もういちどるみなす"},
	{id : 804, name : "HAPPY PARTY TRAIN", credit : "Aqours(アクア)", reading : "はっぴーぱーてぃーとれいん"},
	{id : 1003, name : "M@STERPIECE", credit : "765PRO ALLSTARS", reading : "ますたーぴーす"},
	{id : 1100, name : "ユメノトビラ", credit : "μ's", reading : "ゆめのとびら"},
	{id : 730, name : "流れ星キセキ", credit : "new generations", reading : "ながれぼしきせき"},
	{id : 144, name : "Wishing", credit : "レム(CV:水瀬いのり)", reading : "うぃっしんぐ"},
	{id : 12, name : "愛してるばんざーい！", credit : "μ's", reading : "あいしてるばんざーい"},
	{id : 37, name : "愛を伝えたいだとか", credit : "あいみょん", reading : "あいをつたえたいだとか"},
	{id : 524, name : "新宝島", credit : "サカナクション", reading : "しんたからじま"},
	{id : 1017, name : "丸の内サディスティック", credit : "椎名林檎", reading : "まるのうちさでぃすてぃっく"},
	{id : 1084, name : "U.S.A.", credit : "DA PUMP", reading : "ゆーえすえー"},
	{id : 1181, name : "レディメイド", credit : "Ado", reading : "れでぃめいど"},
	{id : 326, name : "キューティーハニー", credit : "倖田來未", reading : "きゅーてぃーはにー"},
	{id : 787, name : "裸の心", credit : "あいみょん", reading : "はだかのこころ"},
	{id : 470, name : "SEASONS", credit : "浜崎あゆみ", reading : "しーずんず"},
	{id : 275, name : "彼氏はいません今夜だけ", credit : "コレサワ", reading : "かれしはいませんこんやだけ"},
	{id : 1183, name : "Lemon", credit : "米津玄師", reading : "れもん"},
	{id : 448, name : "さよならエレジー", credit : "菅田将暉", reading : "さようならえれじー"},
	{id : 429, name : "サウダージ", credit : "ポルノグラフィティ", reading : "さうだーじ"},
	{id : 371, name : "Get Wild", credit : "TM NETWORK", reading : "げっとわいるど"},
	{id : 8, name : "愛が呼ぶほうへ", credit : "ポルノグラフィティ", reading : "あいがよぶほうへ"},
	{id : 1010, name : "瞬き", credit : "back number", reading : "まばたき"},
	{id : 306, name : "君じゃなきゃダメみたい", credit : "大石昌良", reading : "きみじゃなきゃだめみたい"},
	{id : 1000, name : "マジLOVE1000％", credit : "ST☆RISH", reading : "まじらぶせんぱーせんと"},
	{id : 110, name : "イケナイ太陽", credit : "ORANGE RANGE", reading : "いけないたいよう"},
	{id : 1156, name : "Real Face", credit : "KAT-TUN", reading : "りあるふぇいす"},
	{id : 487, name : "SHAMROCK", credit : "UVERworld", reading : "しゃむろっく"},
	{id : 116, name : "イチブトゼンブ", credit : "B'z", reading : "いちぶとぜんぶ"},
	{id : 238, name : "帰り道", credit : "八九寺真宵(加藤英美里)", reading : "かえりみち 物語シリーズ"},
	{id : 806, name : "ハッピー☆マテリアル", credit : "麻帆良学園中等部2-A(4月)", reading : "はっぴーまてりある"},
	{id : 350, name : "CLEAR", credit : "坂本真綾", reading : "くりあ"},
	{id : 393, name : "恋をしたのは", credit : "Aiko", reading : "こいをしたのは"},
	{id : 620, name : "タキシード・ミラージュ", credit : "小坂明子", reading : "たきしーどみらーしゅ"},
	{id : 655, name : "津軽海峡冬景色", credit : "石川さゆり", reading : "つがるかいきょうふゆげしき"},
	{id : 419, name : "コワレヤスキ", credit : "Guilty Kiss", reading : "こわれやすき"},
	{id : 807, name : "happily ever after", credit : "中川翔子", reading : "はっぴりーえヴぁーあふたー"},
	{id : 1064, name : "もってけ! セーラーふく", credit : "平野綾,加藤英美里,福原香織,遠藤綾", reading : "もってけせーらーふく"},
	{id : 786, name : "はじめてのチュウ", credit : "あんしんパパ", reading : "はじめてのちゅう"},
	{id : 108, name : "行くぜっ!怪盗少女", credit : "ももいろクローバーZ", reading : "いくぜっかいとうしょうじょ"},
	{id : 840, name : "ハルジオン", credit : "YOASOBI", reading : "はるじおん"},
	{id : 157, name : "うまぴょい伝説", credit : "和氣あず未、高野麻里佳、Machico", reading : "うまぴょいでんせつ"},
	{id : 270, name : "からくりピエロ", credit : "40mP feat. 初音ミク", reading : "からくりぴえろ"},
	{id : 838, name : "ハルカ", credit : "YOASOBI", reading : "はるか"},
	{id : 513, name : "ジリティック♡BEGINNER", credit : "ワルキューレ", reading : "じりてぃっくびぎなー"},
	{id : 811, name : "花ざかりWeekend✿", credit : "4 Luxury", reading : "はなざかりういーくえんど"},
	{id : 1206, name : "ワガママMIRROR HEART", credit : "大橋彩香", reading : "わがままみらーはーと"},
	{id : 54, name : "アゲハ蝶", credit : "ポルノグラフィティ", reading : "あげはちょう"},
	{id : 769, name : "ノーザンクロス", credit : "May'n、中島愛", reading : "のーざんくろす"},
	{id : 274, name : "カルマ", credit : "BUMP OF CHICKEN", reading : "かるま"},
	{id : 363, name : "群青", credit : "YOASOBI", reading : "ぐんじょう"},
	{id : 588, name : "千本桜", credit : "黒うさP feat. 初音ミク", reading : "せんぼんざくら"},
	{id : 913, name : "ふたりの世界", credit : "あいみょん", reading : "ふたりのせかい"},
	{id : 662, name : "TT", credit : "TWICE", reading : "てぃーてぃー"},
	{id : 1095, name : "ゆずれない願い", credit : "田村直美", reading : "ゆずれないねがい"},
	{id : 976, name : "POP STAR", credit : "平井堅", reading : "ぽっぷすたー"},
	{id : 902, name : "Fantastic future", credit : "田村ゆかり", reading : "ふぁんたすてぃっくひゅーちゃー"},
	{id : 924, name : "black bullet", credit : "fripSide", reading : "ぶらっくぶれっと"},
	{id : 298, name : "ギミー!レボリューション", credit : "内田真礼", reading : "ぎみーれぼりゅーしょん"},
	{id : 211, name : "乙女式れんあい塾", credit : "矢澤にこ,東條希", reading : "おとめしきれんあいじゅく"},
	{id : 667, name : "Daydream cafe", credit : "Petit Rabbit's", reading : "でいどりーむかふぇ"},
	{id : 773, name : "ノーポイッ!", credit : "Petit Rabbit's", reading : "のーぽいっ"},
	{id : 1019, name : "満月の夜なら", credit : "あいみょん", reading : "まんげつのよるなら"},
	{id : 403, name : "ここでキスして。", credit : "椎名林檎", reading : "ここできすして"},
	{id : 691, name : "慟哭", credit : "工藤静香", reading : "どうこく"},
	{id : 896, name : "First Love", credit : "宇多田ヒカル", reading : "ふぁーすとらぶ"},
	{id : 395, name : "香水", credit : "瑛人", reading : "こうすい"},
	{id : 360, name : "紅蓮の弓矢", credit : "Linked Horizon", reading : "ぐれんのゆみや"},
	{id : 901, name : "FANTASTIC BABY", credit : "BIGBANG", reading : "ふぁんたしーべいべー"},
	{id : 1004, name : "まちがいさがし", credit : "菅田将暉", reading : "まちがいさがし"},
	{id : 1195, name : "ロビンソン", credit : "スピッツ", reading : "ろびんそん"},
	{id : 791, name : "Butterfly Kiss", credit : "米倉千尋", reading : "ばたふらいきす"},
	{id : 180, name : "ETERNAL BLAZE", credit : "水樹奈々", reading : "えたーなるぶれいず"},
	{id : 1189, name : "Rolling star", credit : "YUI", reading : "ろーりんぐすたー"},
	{id : 276, name : "カレンダーガール", credit : "STAR☆ANIS", reading : "かれんだーがーる"},
	{id : 386, name : "恋のMoonlight", credit : "REDALiCE feat. 犬山たまき", reading : "こいのむーんらいと"},
	{id : 958, name : "ボーイフレンド", credit : "Aiko", reading : "ぼーいふれんど"},
	{id : 331, name : "ギラギラ", credit : "Ado", reading : "ぎらぎら"},
	{id : 918, name : "冬物語", credit : "三代目J Soul Brothers from EXILE TRIBE", reading : "ふゆものがたり"},
	{id : 862, name : "ひぐらしのなく頃に", credit : "島みやえい子", reading : "ひぐらしのなくころに"},
	{id : 583, name : "接吻", credit : "ORIGINAL LOVE", reading : "せっぷん"},
	{id : 692, name : "透明人間", credit : "東京事変", reading : "とうめいにんげん"},
	{id : 624, name : "だってアタシのヒーロー。", credit : "LiSA", reading : "だってあたしのひーろー"},
	{id : 570, name : "聖少女領域", credit : "ALI PROJECT", reading : "せいしょうじょりょういき"},
	{id : 821, name : "はなまるぴっぴはよいこだけ", credit : "A応P", reading : "はなまるぴっぴはよいこだけ"},
	{id : 153, name : "打上花火", credit : "DAOKO、米津玄師", reading : "うちあげはなび"},
	{id : 834, name : "バラライカ", credit : "月島きらり", reading : "ばららいか"},
	{id : 770, name : "Northern lights", credit : "林原めぐみ", reading : "のーざんらいつ"},
	{id : 232, name : "only my railgun", credit : "fripSide", reading : "おんりーまいれーるがん"},
	{id : 979, name : "ポニーテールとシュシュ", credit : "AKB48", reading : "ぽにーてーるとしゅしゅ"},
	{id : 742, name : "夏祭り", credit : "Whiteberry", reading : "なつまつり"},
	{id : 21, name : "愛のうた", credit : "倖田來未", reading : "あいのうた"},
	{id : 261, name : "奏", credit : "スキマスイッチ", reading : "かなで"},
	{id : 409, name : "God Bless You", credit : "ワルキューレ", reading : "ごっどぶれすゆー"},
	{id : 607, name : "ダイアモンドクレバス", credit : "シェリル・ノーム(May'n)", reading : "だいあもんどくればす"},
	{id : 279, name : "変わらないもの", credit : "奥華子", reading : "かわらないもの"},
	{id : 44, name : "赤い糸", credit : "コブクロ", reading : "あかいいと"},
	{id : 126, name : "いのちの名前", credit : "平原綾香", reading : "いのちのなまえ"},
	{id : 206, name : "おじゃま虫", credit : "DECO*27 feat. 初音ミク", reading : "おじゃまむし"},
	{id : 953, name : "ヘビーローテーション", credit : "AKB48", reading : "へびーろーてーしょん"},
	{id : 925, name : "プラネタリウム", credit : "大塚愛", reading : "ぷらねたりうむ"},
	{id : 1209, name : "私、アイドル宣言", credit : "HoneyWorks feat. mona（夏川椎菜）", reading : "わたしあいどるせんげん"},
	{id : 881, name : "ひまわりの約束", credit : "秦基博", reading : "ひまわりのやくそく"},
	{id : 1082, name : "U&I", credit : "放課後ティータイム", reading : "ゆーあんどあい"},
	{id : 857, name : "ビードロ模様", credit : "やなぎなぎ", reading : "びーどろもよう"},
	{id : 1185, name : "恋愛裁判", credit : "40mP feat. 初音ミク", reading : "れんあいさいばん"},
	{id : 603, name : "空も飛べるはず", credit : "スピッツ", reading : "そらもとべるはず"},
	{id : 741, name : "夏の幻", credit : "GARNET CROW", reading : "なつのまぼろし"},
	{id : 91, name : "歩いて帰ろう", credit : "斉藤和義", reading : "あるいてかえろう"},
	{id : 674, name : "デリケートに好きして", credit : "太田貴子", reading : "でりけーとにすきして"},
	{id : 1102, name : "夢みたあとで", credit : "GARNET CROW", reading : "ゆめみたあとで"},
	{id : 907, name : "For フルーツバスケット", credit : "岡崎律子", reading : "ふぉーふるーつばすけっと"},
	{id : 56, name : "朝を呑む", credit : "バルーン feat. 初音ミク", reading : "あさをのむ"},
	{id : 852, name : "ハロ/ハワユ", credit : "ナノウ feat. 初音ミク", reading : "はろはわゆ"},
	{id : 1028, name : "ミュージック・アワー", credit : "ポルノグラフィティ", reading : "みゅーじっくあわー"},
	{id : 561, name : "砂の惑星", credit : "ハチ feat. 初音ミク", reading : "すなのわくせい"},
	{id : 106, name : "イエスタデイ", credit : "Official髭男dism", reading : "いえすたでい"},
	{id : 751, name : "虹", credit : "菅田将暉", reading : "にじ"},
	{id : 309, name : "君のうた", credit : "嵐", reading : "きみのうた"},
	{id : 586, name : "前前前世", credit : "RADWIMPS", reading : "ぜんぜんぜんせい"},
	{id : 128, name : "イマココ", credit : "東山奈央", reading : "いまここ"},
	{id : 1031, name : "未来へ", credit : "Kiroro", reading : "みらいへ"},
	{id : 1076, name : "やさしさで溢れるように", credit : "JUJU", reading : "やさしさであふれるように"},
	{id : 379, name : "恋するフォーチュンクッキー", credit : "AKB48", reading : "こいするふぉーちゅんくっきー"},
	{id : 702, name : "ときめきポポロン♪", credit : "チマメ隊", reading : "ときめきぽぽろん"},
	{id : 981, name : "炎", credit : "LiSA", reading : "ほむら"},
	{id : 1033, name : "味楽る!ミミカナンバーワン", credit : "おみむらまゆこ", reading : "みらくるみみかなんばーわん"},
	{id : 1198, name : "ロマンティックあげるよ", credit : "橋本潮", reading : "ろまんてぃっくあげるｙｐ"},
	{id : 1214, name : "私はドキンちゃん", credit : "ドリーミング", reading : "わたしはどきんちゃん"},
	{id : 550, name : "スタートライン!", credit : "せな,りえ from AIKATSU☆STARS!", reading : "すたーとらいん"},
	{id : 399, name : "GO MY WAY!!", credit : "天海春香,水瀬伊織,高槻やよい", reading : "ごーまいーうぇい"},
	{id : 735, name : "夏色えがおで1,2,Jump!", credit : "μ's(ミューズ)", reading : "なついろえがおでわんとぅーじゃんぷ"},
	{id : 382, name : "恋になりたいAQUARIUM", credit : "Aqours", reading : "こいになりたいあくありうむ"},
	{id : 201, name : "O-Ku-Ri-Mo-No Sunday!", credit : "久川颯(長江里加),久川凪(立花日菜)", reading : "おくりものさんでー"},
	{id : 220, name : "おねだり Shall We〜?", credit : "前川みく(高森奈津美)", reading : "おねだりしぇるうぃー"},
	{id : 327, name : "Cutie Panther", credit : "BiBi", reading : "きゅーてぃーぱんさ"},
	{id : 200, name : "オーバーマスター", credit : "プロジェクトフェアリー", reading : "おーばーますたー"},
	{id : 20, name : "アイドル活動!", credit : "STAR☆ANIS,AIKATSU☆STARS!", reading : "あいどるかつどう"},
	{id : 217, name : "お願い!シンデレラ", credit : "CINDERELLA PROJECT", reading : "おねがいしんでれら"},
	{id : 713, name : "ドライフラワー", credit : "優里", reading : "どらいふらわー"},
	{id : 644, name : "チェリー", credit : "スピッツ", reading : "ちぇりー"},
	{id : 255, name : "カタオモイ", credit : "Aimer", reading : "かたおもい"},
	{id : 642, name : "小さな恋のうた", credit : "MONGOL800", reading : "ちいさなこいのうた"},
	{id : 461, name : "366日", credit : "HY", reading : "さんびゃくろくじゅうろくにち"},
	{id : 145, name : "WILL", credit : "米倉千尋", reading : "うぃる"},
	{id : 980, name : "微笑みの爆弾", credit : "馬渡松子", reading : "ほほえみのばくだん"},
	{id : 587, name : "センチメートル", credit : "the peggies(ザ・ペギーズ)", reading : "せんちめーとる"},
	{id : 192, name : "Angelic Angel", credit : "μ's", reading : "えんじぇりっくえんじぇる"},
	{id : 1043, name : "芽ぐみの雨", credit : "やなぎなぎ", reading : "めぐみのあめ"},
	{id : 745, name : "涙そうそう", credit : "夏川りみ", reading : "なみだそうそう"},
	{id : 237, name : "楓", credit : "スピッツ", reading : "かえで"},
	{id : 813, name : "花束を君に", credit : "宇多田ヒカル", reading : "はなたばをきみに"},
	{id : 682, name : "点描の唄", credit : "Mrs. GREEN APPLE feat. 井上苑子", reading : "てんびょうのうた"},
	{id : 316, name : "君をのせて", credit : "井上あずみ", reading : "きみをのせて"},
	{id : 1167, name : "ルージュの伝言", credit : "松任谷由実", reading : "るーじゅのでんごん"},
	{id : 675, name : "テルーの唄", credit : "手嶌葵", reading : "てるーのうた"},
	{id : 244, name : "崖の上のポニョ", credit : "大橋のぞみ、藤岡藤巻", reading : "がけのうえのぽにょ"},
	{id : 282, name : "カントリーロード", credit : "本名陽子", reading : "かんとりーろーど"},
	{id : 772, name : "No brand girls", credit : "μ's", reading : "のーぶらんどがーる"},
	{id : 843, name : "ハルノヒ", credit : "あいみょん", reading : "はるのひ"},
	{id : 819, name : "HANABI", credit : "Mr.Children", reading : "はなび"},
	{id : 23, name : "愛のかたまり", credit : "KinKi Kids", reading : "あいのかたまり"},
	{id : 378, name : "恋心", credit : "相川七瀬", reading : "こいごころ"},
	{id : 288, name : "キセキ", credit : "GReeeeN", reading : "きせき"},
	{id : 948, name : "Baby Sweet Berry Love", credit : "小倉唯", reading : "べいびーすうぃーとべりーらぶ"},
	{id : 897, name : "FIRE!!", credit : "和田光司", reading : "ふぁいやー"},
	{id : 442, name : "The Biggest Dreamer", credit : "和田光司", reading : "ざびっがすとどりーまー"},
	{id : 717, name : "ドリームパレード", credit : "i☆Ris", reading : "どりーむぱれーど"},
	{id : 1041, name : "Make it!", credit : "i☆Ris", reading : "めいくいっと"},
	{id : 301, name : "君色に染まる", credit : "TOKOTOKO(西沢さんP) feat. GUMI", reading : "きみいろにそまる"},
	{id : 696, name : "遠いこの街で", credit : "皆谷尚美", reading : "とおいこのまちで"},
	{id : 566, name : "S(mile)ING!", credit : "島村卯月(大橋彩香)", reading : "すまいりんぐ"},
	{id : 954, name : "heavenly days", credit : "新垣結衣", reading : "へぶんりーでいず"},
	{id : 1093, name : "雪の華", credit : "中島美嘉", reading : "ゆきのはな"},
	{id : 842, name : "春泥棒", credit : "ヨルシカ", reading : "はるどろぼう"},
	{id : 839, name : "春風", credit : "Rihwa", reading : "はるかぜ"},
	{id : 1153, name : "LA・LA・LA LOVE SONG", credit : "久保田利伸", reading : "ららららぶそんぐ"},
	{id : 551, name : "スターラブレイション", credit : "ケラケラ", reading : "すたーらぶれいしょん"},
	{id : 1139, name : "Love so sweet", credit : "嵐", reading : "らぶそーすいーと"},
	{id : 790, name : "Butterfly", credit : "木村カエラ", reading : "ばたふらい  "},
	{id : 1221, name : "One Love", credit : "嵐", reading : "わんらぶ"},
	{id : 36, name : "愛をこめて花束を", credit : "Superfly", reading : "あいをこめてはなたばを"},
	{id : 146, name : "上を向いて歩こう", credit : "坂本九", reading : "うえをむけてあるこう"},
	{id : 1117, name : "夜空ノムコウ", credit : "SMAP", reading : "よるぞらのむこう"},
	{id : 1208, name : "わたがし", credit : "Back number", reading : "わたがし"},
	{id : 973, name : "星のダイアローグ", credit : "スタァライト九九組", reading : "ほしのだいあろーぐ"},
	{id : 636, name : "DANZEN! ふたりはプリキュア", credit : "五條真由美", reading : "だんぜんふたりはぷりきゅあ"},
	{id : 1032, name : "Miracle Go!プリンセスプリキュア", credit : "礒部花凜", reading : "みらくるごーぷりんせすぷりきゅあ"},
	{id : 928, name : "プリキュア5、スマイル go go!", credit : "工藤真由", reading : "ぷりきゅあふぁいぶすまいるごーごー"},
	{id : 1179, name : "Let's go!スマイルプリキュア!", credit : "池田彩", reading : "れっつごーすまいるぷりきゅあ"},
	{id : 1108, name : "夜明け生まれ来る少女", credit : "高橋洋子", reading : "よあけにうまれくるしょうじょ"},
	{id : 1212, name : "わたしの恋はホッチキス", credit : "放課後ティータイム", reading : "わたしのこいはほっちきす"},
	{id : 343, name : "Good-bye days", credit : "YUI", reading : "ぐっばいでいず"},
	{id : 144, name : "wishing", credit : "レム(CV:水瀬いのり)", reading : "うぃっしんぐ"},
	{id : 330, name : "キラキラ", credit : "aiko", reading : "きらきら"},
	{id : 810, name : "花", credit : "ORANGE RANGE", reading : "はな"},
	{id : 256, name : "かたち あるもの", credit : "柴咲コウ", reading : "かたちあるもの"},
	{id : 427, name : "Sign", credit : "Mr.Children", reading : "さいん"},
	{id : 62, name : "明日への扉", credit : "I WiSH", reading : "あすへのとびら"},
	{id : 303, name : "キミがいれば", credit : "伊織", reading : "きみがいれば"},
	{id : 557, name : "staple stable", credit : "戦場ヶ原ひたぎ(斎藤千和)", reading : "すてーぷるすてーぶる 物語シリーズ"},
	{id : 771, name : "ノーダウト", credit : "Official髭男dism", reading : "のーだうと"},
	{id : 515, name : "シル・ヴ・プレジデント", credit : "P丸様。", reading : "しるヴぷれじでんと　しるぷれ"},
	{id : 502, name : "純情スカート", credit : "40mP feat. 初音ミク", reading : "じゅんじょうすかーと"},
	{id : 340, name : "金曜日のおはよう -another story-", credit : "HoneyWorks feat. 成海聖奈(CV 雨宮天)", reading : "きんようびのおはようあなざーすとーりー"},
	{id : 868, name : "ヒッチコック", credit : "ヨルシカ", reading : "ひっちこっく"},
	{id : 725, name : "ナイショの話", credit : "ClariS", reading : "ないしょのはなし"},
	{id : 1050, name : "memories", credit : "大槻マキ", reading : "めもりーず"},
	{id : 789, name : "butter-Fly", credit : "和田光司", reading : "ばたふらい "},
	{id : 70, name : "アナタノオト", credit : "ランカ・リー(中島愛)", reading : "あなたのおと"},
	{id : 507, name : "少年時代", credit : "井上陽水", reading : "しょうねんじだい"},
	{id : 977, name : "にっぽん昔ばなし", credit : "花頭巾", reading : "ほっぽんむかしばなし"},
	{id : 97, name : "アンパンマンのマーチ", credit : "ドリーミング", reading : "あんぱんまんのまーち"},
	{id : 1085, name : "勇気100%", credit : "光GENJI", reading : "ゆうきひゃくぱーせんと"},
	{id : 595, name : "卒業写真", credit : "松任谷由実", reading : "そつぎょうしゃしん"},
	{id : 443, name : "サボテンの花", credit : "財津和夫", reading : "さぼてんのはな"},
	{id : 1009, name : "真夏の果実", credit : "サザンオールスターズ", reading : "まなつのかじつ"},
	{id : 271, name : "硝子の少年", credit : "KinKi Kids", reading : "がらすのしょうねん"},
	{id : 1060, name : "もう恋なんてしない", credit : "槇原敬之", reading : "もうこいなんてしない"},
	{id : 851, name : "Hello, my friend", credit : "松任谷由実", reading : "はろーまいふれんど"},
	{id : 919, name : "PRIDE", credit : "今井美樹", reading : "ぷらいど"},
	{id : 1197, name : "ロマンスの神様", credit : "広瀬香美", reading : "ろまんすのかみさま"},
	{id : 740, name : "夏の日の1993", credit : "class", reading : "なつのひのないてぃんないんてぃすりー"},
	{id : 87, name : "A・RA・SHI", credit : "嵐", reading : "あらし"},
	{id : 1074, name : "優しい彗星", credit : "YOASOBI", reading : "やさしいすいせい"},
	{id : 508, name : "少年よ我に帰れ", credit : "やくしまるえつこメトロオーケストラ", reading : "しょうねんよわれにかえれ"},
	{id : 289, name : "奇想天外ふしぎをどうぞ", credit : "野田愛実", reading : "きそうてんがいふしぎをどうぞ"},
	{id : 1180, name : "Let it go~ありのままで~", credit : "松たか子", reading : "れっといっとごー"},
	{id : 210, name : "乙女解剖", credit : "DECO*27 feat. 初音ミク", reading : "おとめかいぼ"},
	{id : 314, name : "君が夢を連れてきた", credit : "ペットな彼女たち", reading : "きみのゆめをつれてきた"},
	{id : 665, name : "DAYS of DASH", credit : "鈴木このみ", reading : "でいずおぶだっしゅ"},
	{id : 1039, name : "夢想歌", credit : "Suara", reading : "むそうか"},
	{id : 1150, name : "ラブレター", credit : "島村卯月,小日向美穂,五十嵐響子", reading : "らぶれたー"},
	{id : 182, name : "ENERGY", credit : "earthmind", reading : "えなじー"},
	{id : 380, name : "恋せよ女の子", credit : "田村ゆかり", reading : "こいせよおんなのこ"},
	{id : 1147, name : "ラブミーギミー", credit : "Tia", reading : "らぶみーぎみー"},
	{id : 49, name : "アクアテラリウム", credit : "やなぎなぎ", reading : "あくあてらりうむ"},
	{id : 708, name : "扉を開けて", credit : "ANZA", reading : "とびらをあけて"},
	{id : 679, name : "天使にふれたよ!", credit : "放課後ティータイム", reading : "てんしにふれたよ"},
	{id : 563, name : "Snow halation", credit : "μ's", reading : "すのーはれーしょん すのはれ スノハレ"},
	{id : 972, name : "星のかけらを探しに行こう Again", credit : "福耳", reading : "ほしのかけらをさはしにいこうあげいん"},
	{id : 750, name : "なんでもないや", credit : "RADWIMPS", reading : "なんでもないや"},
	{id : 1125, name : "らいおんハート", credit : "SMAP", reading : "らいおんはーと"},
	{id : 194, name : "大きな古時計", credit : "平井堅", reading : "おおきなふるとけい"},
	{id : 817, name : "花の名", credit : "BUMP OF CHICKEN", reading : "はなのな"},
	{id : 151, name : "うたかた花火", credit : "supercell", reading : "うたかたはなび"},
	{id : 971, name : "星に願いを", credit : "Ned Washington", reading : "ほしにねがいを"},
	{id : 1215, name : "私へ", credit : "supercell", reading : "わたしへ"},
	{id : 1052, name : "メランコリック", credit : "Junky feat. 鏡音リン", reading : "めらんこりっく"},
	{id : 999, name : "魔女っ子メグちゃん", credit : "前川陽子", reading : "まじょっこめぐちゃん"},
	{id : 509, name : "ショコラに夢中", credit : "野本かりあ", reading : "しょこらにむちゅう"},
	{id : 437, name : "さくらぼっち", credit : "コアラモード.", reading : "さくらぼっち"},
	{id : 357, name : "グレゴリオ", credit : "古川本舗 feat. ちびた", reading : "ぐれごりお"},
	{id : 778, name : "Party Love〜おっきくなりたい〜", credit : "RO-KYU-BU!", reading : "ぱーてぃーらぶおっきくなりたい"},
	{id : 737, name : "夏恋花火", credit : "40mP feat. シャノ", reading : "なつこいはなび"},
	{id : 1044, name : "（め）組のひと", credit : "ラッツ&スター", reading : "めぐみのひと め組のひと (め)組のひと"},
	{id : 532, name : "睡蓮花", credit : "湘南乃風", reading : "すいれんか"},
	{id : 975, name : "HOT LIMIT", credit : "T.M.Revolution", reading : "ほっとりみっと"},
	{id : 75, name : "あの夢をなぞって", credit : "YOASOBI", reading : "あのゆめをなぞって"},
	{id : 187, name : "Everyday、カチューシャ", credit : "AKB48", reading : "えぶりでいかちゅーしゃ"},
	{id : 1107, name : "夜明けと蛍", credit : "n-buna", reading : "よあけとほたる"},
	{id : 1127, name : "LIFE 〜目の前の向こうへ〜", credit : "関ジャニ∞", reading : "らいふめのまえのむこうへ"},
	{id : 1029, name : "Music S.T.A.R.T!!", credit : "μ's", reading : "みゅーじっくすたーと"},
	{id : 281, name : "感謝カンゲキ雨嵐", credit : "嵐", reading : "かんしゃかんげきあめあらし"},
	{id : 734, name : "夏色", credit : "ゆず", reading : "なついろ"},
	{id : 683, name : "トゥインクル", credit : "Junky feat. 鏡音リン", reading : "とぅいんくる"},
	{id : 829, name : "パプリカ", credit : "米津玄師", reading : "ぱぷりか"},
	{id : 5, name : "愛唄", credit : "GReeeeN", reading : "あいうた"},
	{id : 473, name : "ジェットコースター・ロマンス", credit : "KinKi Kids", reading : "じぇっとこーすたーろまんす"},
	{id : 392, name : "koi-wazurai", credit : "King & Prince", reading : "こいわずらい"},
	{id : 27, name : "I promise", credit : "King & Prince", reading : "あいぷろみす"},
	{id : 605, name : "Darling", credit : "西野カナ", reading : "だーりん"},
	{id : 584, name : "背中越しのチャンス", credit : "亀と山P", reading : "せなかごしのちゃんす"},
	{id : 410, name : "言葉より大切なもの", credit : "嵐", reading : "ことばよりたいせつなもの"},
	{id : 1158, name : "ローリンガール", credit : "wowaka feat. 初音ミク", reading : "りーりんがーる"},
	{id : 511, name : "白雪姫", credit : "Flower", reading : "しらゆきひめ"},
	{id : 451, name : "さよならミッドナイト", credit : "大柴広己", reading : "さよならみっどないと"},
	{id : 518, name : "白い雪のプリンセスは", credit : "のぼる↑ feat. 初音ミク", reading : "しろいゆきのぷりんせすは"},
	{id : 1088, name : "憂、燦々", credit : "クリープハイプ", reading : "ゆうさんさん"},
	{id : 25, name : "愛の標識", credit : "クリープハイプ", reading : "あいのひょうしき"},
	{id : 670, name : "手紙 ～拝啓 十五の君へ～", credit : "アンジェラ・アキ", reading : "てがみはいけいじゅうごのきみ"},
	{id : 490, name : "Shangri-La", credit : "angela", reading : "しゃんぐりら"},
	{id : 749, name : "奈落の花", credit : "島みやえい子", reading : "ならくのはな"},
	{id : 685, name : "TO BE", credit : "浜崎あゆみ", reading : "とぅーびー"},
	{id : 329, name : "きゅんっ！ヴァンパイアガール", credit : "星井美希(CV.長谷川明子)", reading : "きゅんっヴぁんばいやがーる"},
	{id : 886, name : "ヒメムラサキ", credit : "水樹奈々", reading : "ひめむらさき"},
	{id : 1024, name : "蛟龍の巫女", credit : "陰陽座", reading : "みずちのみこ"},
	{id : 920, name : "プライド～嘆きの旅～", credit : "AKINO", reading : "ぷらいどなげきのたび"},
	{id : 147, name : "Voyage", credit : "浜崎あゆみ", reading : "ヴぉいやーじゅ"},
	{id : 929, name : "Precious", credit : "May J.", reading : "ぷりしあす"},
	{id : 92, name : "アンインストール", credit : "石川智晶", reading : "あんいんすとーる"},
	{id : 618, name : "だから僕は音楽を辞めた", credit : "ヨルシカ", reading : "だからぼくはおんがくをやめた"},
	{id : 489, name : "シャルル", credit : "バルーン feat. v flower", reading : "しゃるる"},
	{id : 341, name : "楔", credit : "奧華子", reading : "くさび"},
	{id : 48, name : "agape", credit : "Melocure", reading : "あがぺ"},
	{id : 556, name : "stay alive", credit : "エミリア(CV：高橋李依)", reading : "すていあらいぶ"},
	{id : 720, name : "ドレミファロンド", credit : "40mP feat. 初音ミク", reading : "どれみふぁろんど"},
	{id : 990, name : "My Dearest", credit : "supercell", reading : "まいでぃあれすと"},
	{id : 319, name : "Catch you catch me", credit : "丹下桜", reading : "きゃっちゆーきゃっちみー"},
	{id : 1129, name : "ラヴァーズ", credit : "7!!", reading : "らヴぁーず lovers"},
	{id : 100, name : "unravel", credit : "TK from 凛として時雨", reading : "あんらべる"},
	{id : 809, name : "バトルフロンティア", credit : "高屋亜希那", reading : "ばとるふふろんてぃあ"},
	{id : 344, name : "KODOU~パーフェクト·ハーモニー", credit : "中田あすみ（七海るちあ）・寺門仁美（宝生波音）・浅野まゆみ（洞院リナ）", reading : "くどうぱーふぇくとはーもにー"},
	{id : 564, name : "スパート！", credit : "松本梨香", reading : "すぱーと"},
	{id : 982, name : "ポルカ·オ·ドルカ", credit : "ニャース(犬山イヌコ)&ノルソル合唱団", reading : "ぽるかおどるか"},
	{id : 404, name : "心絵", credit : "Road of Major", reading : "こころえ"},
	{id : 847, name : "晴れてハレルヤ", credit : "奥井亜紀", reading : "はれてはれるや"},
	{id : 226, name : "オラはにんきもの", credit : "こぶしファクトリー", reading : "おらはにんきもの"},
	{id : 468, name : "Secret of my heart", credit : "倉木麻衣", reading : "しーくれっとおぶまいはーと"},
	{id : 41, name : "青空Jumping Heart", credit : "Aqours", reading : "あおぞらじゃんぴんぐはーと"},
	{id : 1145, name : "Love marginal", credit : "Printemps", reading : "らぶまーじなる"},
	{id : 633, name : "Dancing stars on me!", credit : "μ's", reading : "だんしんぐすたーずおんみー"},
	{id : 877, name : "微熱からMystery", credit : "lily white", reading : "びねつからみすてりー"},
	{id : 888, name : "Pure girls project", credit : "Printemps", reading : "ぴゅあがーるずぷろじぇくと"},
	{id : 1023, name : "未熟DREAMER", credit : "Aqours(アクア)", reading : "みじゅくどりーまー"},
	{id : 292, name : "きっと青春が聞こえる", credit : "μ's", reading : "きっとせいしゅんがきこえる"},
	{id : 310, name : "君のこころは輝いてるかい？", credit : "Aqours(アクア)", reading : "きみのこころはかがやいてるかい"},
	{id : 1219, name : "1・2・3", credit : "After the Rain", reading : "わんつーすりー 123 １２３"},
	{id : 768, name : "脳裏上のクラッカー", credit : "ずっと真夜中でいいのに。", reading : "のうりうえのくらっかー"},
	{id : 252, name : "風待ちジェット", credit : "坂本真綾", reading : "かぜまちじぇっと"},
	{id : 946, name : "平行線", credit : "さユり", reading : "へいこうせん"},
	{id : 721, name : "とろあまちゅ", credit : "椎名ひかり", reading : "とろあまちゅ"},
	{id : 969, name : "ポケッターリ モンスターリ", credit : "可名", reading : "ぽけったーりもんすたーり"},
	{id : 885, name : "秘密のトワレ", credit : "一ノ瀬志希(CV.藍原ことみ)", reading : "ひみつのとわれ"},
	{id : 209, name : "踊", credit : "Ado", reading : "おど"},
	{id : 482, name : "Shine‼︎", credit : "CINDERELLA PROJECT", reading : "しゃーいん"},
	{id : 175, name : "笑顔のゲンキ", credit : "SMAP", reading : "えがおのげんき"},
	{id : 139, name : "ウィーアー!", credit : "きただにひろし", reading : "うぃーあー we are"},
	{id : 216, name : "おどるポンポコリン", credit : "B.B.クィーンズ", reading : "おどるぽんぽりごん"},
	{id : 398, name : "GHOST SWEEPER", credit : "原田千栄", reading : "ごーすとすいーぱー"},
	{id : 931, name : "ブルーウォーター", credit : "森川美穂", reading : "ぶるーうぉーたー"},
	{id : 174, name : "笑顔に会いたい", credit : "濱田理恵", reading : "えがおにあいたい"},
	{id : 95, name : "アンバランスなKissをして", credit : "高橋ひろ", reading : "あんばらんすなきすをして"},
	{id : 777, name : "PARTY☆NIGHT", credit : "D.U.P.(真田アサミ・沢城みゆき・氷上恭子)", reading : "ぱーてぃーないと"},
	{id : 367, name : "消せない罪", credit : "北出菜奈", reading : "けせないつみ"},
	{id : 6, name : "I am", credit : "hitomi", reading : "あいえむ"},
	{id : 1168, name : "ループ", credit : "坂本真綾", reading : "るーぷ"},
	{id : 1141, name : "love destiny", credit : "堀江由衣", reading : "らぶですてぃにー"},
	{id : 114, name : "いちごコンプリート", credit : "千葉紗子,折笠富美子,川澄綾子,能登麻美子", reading : "いちごこんぷりーと"},
	{id : 370, name : "Get Over", credit : "Dream", reading : "げっとおーばー"},
	{id : 430, name : "逆さまの蝶", credit : "Snow", reading : "さかさまのちょう"},
	{id : 907, name : "for フルーツバスケット", credit : "岡崎律子", reading : "ふぉーふるーつばすけっと"},
	{id : 48, name : "Agape", credit : "Melocure", reading : "あがぺ"},
	{id : 154, name : "美しきもの", credit : "Sound Horizon", reading : "うつくしきもの"},
	{id : 454, name : "サリシノハラ", credit : "みきとP feat. 初音ミク", reading : "さりしのはら"},
	{id : 1008, name : "マトリョシカ", credit : "ハチ feat. 初音ミク,GUMI", reading : "まとりょしか"},
	{id : 1113, name : "吉原ラメント", credit : "亜沙 feat. 重音テト", reading : "よしわららめんと"},
	{id : 1063, name : "モザイクロール", credit : "DECO*27 feat. GUMI", reading : "もざいくろーる"},
	{id : 876, name : "独りんぼエンヴィー", credit : "電ポルP feat. 初音ミク", reading : "ひとりんぼえんヴぁー"},
	{id : 767, name : "脳漿炸裂ガール", credit : "れるりり feat. 初音ミク, GUMI", reading : "のうしょうさくれつがーる"},
	{id : 687, name : "東京テディベア", credit : "Neru feat. 鏡音リン", reading : "とうきょうてでぃべあ"},
	{id : 1122, name : "弱虫モンブラン", credit : "DECO*27 feat. GUMI", reading : "よわむしもんぶらん"},
	{id : 190, name : "えれくとりっく・えんじぇぅ", credit : "ヤスオ feat. 初音ミク", reading : "えれくとりっくえんじぇぅ"},
	{id : 278, name : "可愛くなりたい", credit : "HoneyWorks feat.成海聖奈（CV：雨宮天）", reading : "かわいくなりたい"},
	{id : 383, name : "コイノシルシ", credit : "神のみぞ知り隊", reading : "こいのしるし"},
	{id : 234, name : "Girlish Lover", credit : "赤崎千夏、田村ゆかり、金元寿子、茅野愛衣", reading : "がーりっしゅらばー"},
	{id : 802, name : "はっぴぃにゅうにゃあ", credit : "井口裕香、伊藤かな恵、竹達彩奈", reading : "はっぴぃにゅうにゃあ"},
	{id : 529, name : "sweets parade", credit : "花澤香菜", reading : "すいーとぱれーど"},
	{id : 160, name : "ultra soul", credit : "B'z", reading : "うるとらそーる"},
	{id : 738, name : "夏のお嬢さん", credit : "榊原郁恵", reading : "なつのおじょうさん"},
	{id : 826, name : "ハネウマライダー", credit : "ポルノグラフィティ", reading : "はねうまらいだー"},
	{id : 196, name : "大阪LOVER", credit : "DREAMS COME TRUE", reading : "おおさからばー"},
	{id : 828, name : "Happiness", credit : "ORANGE RANGE", reading : "はぴねす"},
	{id : 339, name : "金曜日のおはよう", credit : "HoneyWorks feat. GUMI", reading : "きんようびのおはよう"},
	{id : 887, name : "115万キロのフィルム", credit : "Official髭男dism", reading : "ひゃくじゅうごまんきろのふぃるむ"},
	{id : 1146, name : "LOVEマシーン", credit : "モーニング娘。", reading : "らぶましーん"},
	{id : 575, name : "世界が終るまでは…", credit : "WANDS", reading : "せかいがおわるまでは"},
	{id : 1101, name : "YUME日和", credit : "島谷ひとみ", reading : "ゆめびより"},
	{id : 1013, name : "守ってあげたい", credit : "松任谷由実", reading : "まもってあげたい"},
	{id : 841, name : "春〜spring〜", credit : "Hysteric Blue", reading : "はるすぷりんぐ"},
	{id : 552, name : "Starry Heavens", credit : "day after tomorrow", reading : "すたーりーへぶんず"},
	{id : 656, name : "ツキアカリのミチシルベ", credit : "ステレオポニー", reading : "つきあかりのみちしるべ"},
	{id : 362, name : "crossing field", credit : "LiSA", reading : "くろっしんぐふぃーるど"},
	{id : 781, name : "HOWEVER", credit : "GLAY", reading : "はうえヴぁー"},
	{id : 198, name : "Automatic", credit : "宇多田ヒカル", reading : "おーとまちっく"},
	{id : 613, name : "Time goes by", credit : "Every Little Thing", reading : "たいむごーずばい"},
	{id : 123, name : "いとしのエリー", credit : "サザンオールスターズ", reading : "いとしのえりー"},
	{id : 984, name : "White Love", credit : "SPEED", reading : "ほわいとらぶ"},
	{id : 464, name : "散歩道", credit : "JUDY AND MARY", reading : "さんぽみち"},
	{id : 634, name : "ダンシング・ヒーロー", credit : "荻野目洋子", reading : "だんしんぐひーろー"},
	{id : 77, name : "Ahoy!!我ら宝鐘海賊団☆", credit : "宝鐘マリン", reading : "あほいわれらほうしょうかいぞくだん"},
	{id : 796, name : "ハッピーウェディング前ソング", credit : "ヤバイTシャツ屋さん", reading : "はっぴーうぇでぃんぐまえそんぐ"},
	{id : 1049, name : "女々しくて", credit : "ゴールデンボンバー", reading : "めめしくて"},
	{id : 995, name : "M@GIC☆", credit : "CINDERELLA PROJECT", reading : "まじっく"},
	{id : 84, name : "アヤノの幸福理論", credit : "じん feat. IA", reading : "あやののこうふくりろん"},
	{id : 33, name : "アイロニ", credit : "majiko", reading : "あいろに"},
	{id : 61, name : "明日への手紙", credit : "手嶌葵", reading : "あすへのてがみ"},
	{id : 608, name : "対象a", credit : "anNina", reading : "たいしょうえー"},
	{id : 1080, name : "you", credit : "癒月", reading : "ゆー"},
	{id : 82, name : "アムリタ", credit : "牧野由依", reading : "あむりた"},
	{id : 1061, name : "もうそう えくすぷれす", credit : "千石撫子(花澤香菜)", reading : "もうそうえくすぷれす もうそう♥えくすぷれす 物語シリーズ"},
	{id : 193, name : "Os-宇宙人", credit : "エリオをかまってちゃん(神聖かまってちゃん)", reading : "おーえすうちゅうじん"},
	{id : 1091, name : "幽霊東京", credit : "Ayase(YOASOBI) feat. 初音ミク", reading : "ゆうれいとうきょう"},
	{id : 1165, name : "relations", credit : "星井美希(長谷川明子)", reading : "りれーしょんず"},
	{id : 384, name : "恋のHamburg", credit : "五十嵐響子(種﨑敦美)", reading : "こいのはんばーぐ"},
	{id : 757, name : "Naked Romance", credit : "小日向美穂(津田美波)", reading : "ねいきっどろまんす"},
	{id : 911, name : "不可思議のカルテ", credit : "桜島麻衣(瀬戸麻沙美),古賀朋絵(東山奈央),双葉理央(種﨑敦美),豊浜のどか(内田真礼),梓川かえで(久保ユリカ),牧之原翔子(水瀬いのり)", reading : "ふかしぎのかるて"},
	{id : 798, name : "ハッピークレセント", credit : "中川かのん(東山奈央)", reading : "はっぴーくれせんと"},
	{id : 850, name : "Hello Alone", credit : "雪ノ下雪乃(早見沙織)、由比ヶ浜結衣(東山奈央)", reading : "はろーあろん"},
	{id : 240, name : "学園天国", credit : "フィンガー5", reading : "がくえんてんごく"},
	{id : 609, name : "ダイナマイトヘブン", credit : "2Shy4U", reading : "だいなまいとへぶん"},
	{id : 295, name : "希望峰", credit : "Strawberry JAM", reading : "きぼうほう"},
	{id : 432, name : "サクラサク", credit : "林原めぐみ", reading : "さくらさく"},
	{id : 610, name : "DIVER#2100", credit : "R.A.M", reading : "だいばーにせんひゃく"},
	{id : 956, name : "ホウキ雲", credit : "RYTHEM", reading : "ほうきぐも"},
	{id : 355, name : "Grip!", credit : "Every Little Thing", reading : "ぐりっぷ"},
	{id : 714, name : "TRUST", credit : "Salia", reading : "とらすと"},
	{id : 892, name : "Believe", credit : "玉置成実", reading : "びりーぶ"},
	{id : 94, name : "あんなに一緒だったのに", credit : "See-Saw", reading : "あんなにいっしょだったのに"},
	{id : 4, name : "I'll be the one", credit : "HΛL", reading : "あいいうびーざわん"},
	{id : 760, name : "ねぇ、", credit : "SHISHAMO", reading : "ねぇ "},
	{id : 1120, name : "夜のピエロ", credit : "Ado", reading : "よるのぴえろ"},
	{id : 93, name : "アンコール", credit : "YOASOBI", reading : "あんこーる"},
	{id : 117, name : "言って。", credit : "ヨルシカ", reading : "いって"},
	{id : 700, name : "トキメキノーツ♪", credit : "のりプロ", reading : "ときめきのーつ"},
	{id : 346, name : "雲と幽霊", credit : "ヨルシカ", reading : "くもとゆうれい"},
	{id : 715, name : "ドラマチック", credit : "Base Ball Bear", reading : "どらまちっく"},
	{id : 616, name : "高嶺の花子さん", credit : "back number", reading : "たかねのはなこさん"},
	{id : 739, name : "夏の扉", credit : "松田聖子", reading : "なつのとびら"},
	{id : 904, name : "ファンファーレ!", credit : "Hey! Say! JUMP", reading : "ふぁんふぁーれ"},
	{id : 499, name : "宿命", credit : "Official髭男dism", reading : "しゅくめい"},
	{id : 115, name : "一度だけの恋なら", credit : "ワルキューレ", reading : "いちどうだけのこいなら"},
	{id : 1062, name : "妄想感傷代償連盟", credit : "DECO*27 feat. 初音ミク", reading : "もうそうかんしょうだいしょうれんめい"},
	{id : 1086, name : "勇気りんりん", credit : "ドリーミング", reading : "ゆうきりんりん"},
	{id : 198, name : "automatic", credit : "宇多田ヒカル", reading : "おーとまちっく"},
	{id : 503, name : "じょいふる", credit : "いきものがかり", reading : "じょいふる"},
	{id : 338, name : "キンモクセイ", credit : "オレンジスパイニクラブ", reading : "きんもくせい"},
	{id : 1015, name : "マリーゴールド", credit : "あいみょん", reading : "まりーごーるど"},
	{id : 304, name : "君がくれた夏", credit : "家入レオ", reading : "きみがくれたなつ"},
	{id : 336, name : "KING", credit : "Kanaria feat. GUMI", reading : "きんぐ"},
	{id : 138, name : "ヴァンパイア", credit : "DECO*27 feat. 初音ミク", reading : "ヴぁんぱいあ"},
	{id : 590, name : "全力少年", credit : "スキマスイッチ", reading : "ぜんりょくしょうねん"},
	{id : 347, name : "Cry Baby", credit : "Official髭男dism", reading : "くらいべいびー"},
	{id : 921, name : "flying", credit : "GARNET CROW", reading : "ふらいんぐ"},
	{id : 779, name : "灰色と青", credit : "米津玄師", reading : "はいいろとあお"},
	{id : 701, name : "ときめきの導火線", credit : "今野友加里", reading : "ときめきのどうかせん"},
	{id : 602, name : "空へ…", credit : "笠原弘子", reading : "そらへ "},
	{id : 1075, name : "優しさの理由", credit : "ChouCho", reading : "やさしいのりゆう"},
	{id : 1174, name : "ルル", credit : "やくしまるえつこ", reading : "るる"},
	{id : 221, name : "おはよう。", credit : "Keno", reading : "おはよう"},
	{id : 1216, name : "わぴこ元気予報!", credit : "内田順子", reading : "わびこげんきよほう"},
	{id : 859, name : "光と影を抱きしめたまま", credit : "田村直美", reading : "ひかりとかげをだきしめたまま"},
	{id : 63, name : "明日への勇気", credit : "吉成圭子", reading : "あすへのゆうき"},
	{id : 471, name : "Sea loves you", credit : "篠塚満由美", reading : "しーらぶゆー"},
	{id : 565, name : "SPIRIT", credit : "PAMELAH", reading : "すぴりっと"},
	{id : 891, name : "Believe ", credit : "Folder5", reading : "びりーぶ"},
	{id : 666, name : "DISCOTHEQUE", credit : "水樹奈々", reading : "でぃすこてぃっく"},
	{id : 1099, name : "夢色パレード", credit : "Rhodanthe*", reading : "ゆめいろぱれーど"},
	{id : 290, name : "キラッ!満開スマイル", credit : "島村卯月,小日向美穂,佐久間まゆ,他", reading : "きたっまんかいすまいる"},
	{id : 846, name : "Palette", credit : "P.C.S.", reading : "ぱれっと"},
	{id : 545, name : "ススメ☆オトメ ~jewel parade~", credit : "CINDERELLA PROJECT", reading : "すすめおとめじゅえるぱれーど"},
	{id : 203, name : "おさかな天国", credit : "柴矢裕美", reading : "おさかなてんごく"},
	{id : 875, name : "ヒトリノ夜", credit : "ポルノグラフィティ", reading : "ひとりのよる"},
	{id : 1164, name : "リライト", credit : "ASIAN KUNG-FU GENERATION", reading : "りらいと"},
	{id : 698, name : "ドーナツホール", credit : "米津玄師(ハチ) feat. GUMI", reading : "どーなつほーる"},
	{id : 463, name : "さんぽ", credit : "井上あずみ", reading : "さんぽ"},
	{id : 249, name : "風のとおり道", credit : "久石譲", reading : "かぜのとおりみち"},
	{id : 1077, name : "やさしさに包まれたなら", credit : "松任谷由実", reading : "やさしさにつつまれたなら"},
	{id : 1067, name : "もののけ姫", credit : "米良美一", reading : "もののけひめ"},
	{id : 119, name : "いつも何度でも", credit : "木村弓", reading : "いつもなんどでも"},
	{id : 578, name : "世界の約束", credit : "倍賞千恵子", reading : "せかいのやくそく"},
	{id : 1045, name : "めぐる季節", credit : "オフ・コース", reading : "めぐるきせつ"},
	{id : 300, name : "君色シグナル", credit : "春奈るな", reading : "きみいろしぐなる"},
	{id : 651, name : "チューリングラブ", credit : "ナナヲアカリ feat. Sou/ピヨ", reading : "ちゅーりんぐらぶ"},
	{id : 963, name : "ボクノート", credit : "スキマスイッチ", reading : "ぼくのーと"},
	{id : 1186, name : "恋愛写真", credit : "大塚愛", reading : "れんあいしゃしん"},
	{id : 1036, name : "Moon Revenge", credit : "三石琴乃、富沢美智恵、久川綾、篠原恵美、深見梨加", reading : "むーんりべんじ"},
	{id : 869, name : "HIT IN THE USA", credit : "BEAT CRUSADERS", reading : "ひっといんざゆーえすえー"},
	{id : 299, name : "君色思い", credit : "SMAP", reading : "きみいろおもい"},
	{id : 1222, name : "ン・パカマーチ", credit : "徳光由香", reading : "んぱかまーち"},
	{id : 18, name : "会いたくて 会いたくて", credit : "西野カナ", reading : "あいたくてあいたくて"},
	{id : 101, name : "いーあるふぁんくらぶ", credit : "みきとP feat. GUMI・鏡音リン", reading : "いーあるふぁんくらぶ"},
	{id : 1056, name : "メルト", credit : "ryo(supercell) feat. 初音ミク", reading : "めると"},
	{id : 654, name : "チルドレンレコード", credit : "じん(自然の敵P) feat. IA", reading : "ちるどれんれこーど"},
	{id : 208, name : "オツキミリサイタル", credit : "じん(自然の敵P) feat. IA", reading : "おつきみりさいたる"},
	{id : 1194, name : "ロストワンの号哭", credit : "Neru feat. 鏡音リン", reading : "ろすとわんのごうこく"},
	{id : 1069, name : "♡桃色片想い♡", credit : "松浦亜弥", reading : "ももいろかたおもい"},
	{id : 96, name : "アンパンマンたいそう", credit : "ドリーミング", reading : "あんぱんまんたいそう"},
	{id : 111, name : "いけないボーダーライン", credit : "ワルキューレ", reading : "いけないぼーだーらいん"},
	{id : 2, name : "あゝオオサカdreamin'night", credit : "どついたれ本舗", reading : "ああおおさかどりみんぐないと"},
	{id : 664, name : "DAYS", credit : "FLOW", reading : "でいず"},
	{id : 365, name : "経験値上昇中☆", credit : "南春香,南夏奈,南千秋", reading : "けいけんちじょうしょうちゅう"},
	{id : 639, name : "Dan Dan Dan", credit : "SUN&LUNAR(桃井はるこ,野川さくら)", reading : "だんだんだん"},
	{id : 214, name : "オトメロディー", credit : "高橋美佳子", reading : "おとめろでぃー"},
	{id : 141, name : "ウィークエンダー", credit : "Hey! Say! JUMP", reading : "うぃーくえんだー"},
	{id : 108, name : "行くぜっ！怪盗少女", credit : "ももいろクローバーZ", reading : "いくぜっかいとうしょうじょ"},
	{id : 1190, name : "ロキ", credit : "みきとP feat. 鏡音リン", reading : "ろき"},
	{id : 845, name : "春を告げる", credit : "yama", reading : "はるをつげる"},
	{id : 543, name : "Squall", credit : "松本英子", reading : "すこーる"},
	{id : 3, name : "Re:Re:", credit : "ASIAN KUNG-FU GENERATION", reading : "あーるいーあーるいー"},
	{id : 712, name : "トライアングラー", credit : "坂本真綾", reading : "どらいあんぐらー"},
	{id : 476, name : "地獄の沙汰も君次第", credit : "地獄の沙汰オールスターズ", reading : "じごくのさたもきみしだい"},
	{id : 462, name : "1/3の純情な感情", credit : "SIAM SHADE", reading : "さんぶんのいちのじゅんじょうなかんじょう"},
	{id : 396, name : "GO ! ! !", credit : "FLOW", reading : "ごー"},
	{id : 638, name : "DAN DAN 心魅かれてく", credit : "FIELD OF VIEW", reading : "だんだんこころひかれてく"},
	{id : 873, name : "ひとりじゃない", credit : "DEEN", reading : "ひとりじゃない"},
	{id : 450, name : "SAYONARAベイベー", credit : "加藤ミリヤ", reading : "さよならべいべー"},
	{id : 1131, name : "ラヴ・イズ・オーヴァー", credit : "欧陽菲菲", reading : "らヴいずおヴぁー love is over"},
	{id : 189, name : "M", credit : "浜崎あゆみ", reading : "えむ"},
	{id : 313, name : "きみの て", credit : "Every Little Thing", reading : "きみのて"},
	{id : 704, name : "渡月橋～君想ふ～", credit : "倉木麻衣", reading : "とげつきょうきみおもう"},
	{id : 1160, name : "Little Wish 〜lyrical step〜", credit : "田村ゆかり", reading : "りとるうぃっしゅりりかるすてっぷ"},
	{id : 805, name : "Happy Halloween", credit : "Junky feat. 鏡音リン", reading : "はっぴーはろうぃん"},
	{id : 1079, name : "ヤミヤミ", credit : "やくしまるえつこ", reading : "やみやみ"},
	{id : 960, name : "僕たちが恋をするの理由", credit : "坂本真綾", reading : "ぼくたちがこいをするりゆう"},
	{id : 417, name : "それは僕たちの奇跡", credit : "μ's", reading : "これはぼくたちのきせき"},
	{id : 792, name : "Hacking to the Gate", credit : "いとうかなこ", reading : "はっきんぐとぅざげーと"},
	{id : 795, name : "Bad Apple!!", credit : "Alstroemeria Records feat. nomico", reading : "ばっどあっぷる"},
	{id : 572, name : "sailing day", credit : "BUMP OF CHICKEN", reading : "せいりんぐでい"},
	{id : 478, name : "シスター", credit : "ポルノグラフィティ", reading : "しすたー"},
	{id : 647, name : "チカっとチカ千花っ♡", credit : "藤原千花(小原好美)", reading : "ちかっとちかちかっ"},
	{id : 414, name : "ごはんはおかず", credit : "放課後ティータイム", reading : "ごはんはおかず"},
	{id : 965, name : "ボクの背中には羽根がある", credit : "KinKi Kids", reading : "ぼくのせなかにははねがある"},
	{id : 544, name : "Zzz", credit : "佐咲紗花", reading : "ずずず"},
	{id : 567, name : "正解はひとつ!じゃない!!", credit : "ミルキィホームズ", reading : "せいかいはひとつじゃない"},
	{id : 416, name : "今宵、月が見えずとも", credit : "ポルノグラフィティ", reading : "こよいつきがみえずとも"},
	{id : 765, name : "ねこ日記", credit : "ランカ・リー(中島愛)", reading : "ねこにっき"},
	{id : 283, name : "ギガアイシテル", credit : "レキシ", reading : "ぎがあいしてる"},
	{id : 531, name : "水平線", credit : "back number", reading : "すいへいせん"},
	{id : 421, name : "最悪な日でもあなたが好き。", credit : "芹澤優", reading : "さいあくなひでもあなたがすき"},
	{id : 441, name : "ザ☆ピ〜ス!", credit : "モーニング娘。", reading : "ざぴーす"},
	{id : 697, name : "遠く遠く", credit : "槇原敬之", reading : "とおくとおく"},
	{id : 1163, name : "流星群", credit : "鬼束ちひろ", reading : "りゅうせいぐん"},
	{id : 143, name : "WISH", credit : "嵐", reading : "ういっしゅ"},
	{id : 938, name : "Flavor Of Life", credit : "宇多田ヒカル", reading : "ふれーばーおぶらいふ flavour of life"},
	{id : 1187, name : "恋愛レボリューション21", credit : "モーニング娘", reading : "れんあいれぼりゅーしょんにじゅういち"},
	{id : 412, name : "粉雪", credit : "レミオロメン", reading : "こなゆき"},
	{id : 754, name : "二足歩行", credit : "DECO*27 feat. 初音ミク", reading : "にそくほこう"},
	{id : 1022, name : "みくみくにしてあげる♪【してやんよ】", credit : "ika feat. 初音ミク", reading : "みくみくにしてあげるしてやんよ"},
	{id : 1201, name : "ロングホープ・フィリア", credit : "菅田将暉", reading : "ろんぐほーぷふぃりあ"},
	{id : 1132, name : "“らしく”いきましょ", credit : "Meu", reading : "らしくいきましょ"},
	{id : 952, name : "ベノム", credit : "かいりきベア feat. v flower", reading : "べのむ"},
	{id : 1115, name : "夜咄ディセイブ", credit : "じん（自然の敵P）feat. IA", reading : "よばなしでぃせいぶ"},
	{id : 150, name : "WATER BLUE NEW WORLD", credit : "Aqours(アクア)", reading : "うぉーたーぶるーにゅーわーるど"},
	{id : 874, name : "「ひとりで生きられそう」って それってねえ、褒めているの?", credit : "Juice=Juice", reading : "ひとりでいきられそうってそれってねえほめているの"},
	{id : 135, name : "インフルエンサー", credit : "乃木坂46", reading : "いんふるえんざー"},
	{id : 1058, name : "moreきゅん奴隷", credit : "戦慄かなの", reading : "もあきゅんどれい"},
	{id : 650, name : "チュープリ", credit : "ZOC", reading : "ちゅーぷり"},
	{id : 854, name : "ヒアルロンリーガール", credit : "ZOC", reading : "ひあるろんりーがーる"},
	{id : 285, name : "如月アテンション", credit : "じん(自然の敵P) feat. IA", reading : "きさらぎあてんしょん"},
	{id : 994, name : "負けないで", credit : "ZARD", reading : "まけないで"},
	{id : 79, name : "アポロ", credit : "ポルノグラフィティ", reading : "あぽろ"},
	{id : 1051, name : "Mela!", credit : "緑黄色社会", reading : "めら"},
	{id : 9, name : "愛されるより 愛したい", credit : "KinKi Kids", reading : "あいされるよりあいしたい"},
	{id : 693, name : "tomorrow never knows", credit : "Mr.Children", reading : "とぅもろーねヴぁーのーず"},
	{id : 398, name : "ghost sweeper", credit : "原田千栄", reading : "ごーすとすいーぱー"},
	{id : 41, name : "青空jumping heart", credit : "Aqours", reading : "あおぞらじゃんぴんぐはーと"},
	{id : 563, name : "snow halation", credit : "μ's", reading : "すのーはれーしょん すのはれ スノハレ"},
	{id : 865, name : "翡翠のまち", credit : "メル feat. 初音ミク", reading : "ひすいのまち"},
	{id : 673, name : "te-yut-te", credit : "フェイP feat. 鏡音リン", reading : "てゆって"},
	{id : 312, name : "君の好きな本", credit : "TOKOTOKO(西沢さんP) feat. GUMI", reading : "きみのすきなほん"},
	{id : 582, name : "セツナトリップ", credit : "Last Note. feat. GUMI", reading : "せつなとりっぷ"},
	{id : 351, name : "繰り返し一粒", credit : "猫虫 feat. 鏡音リン", reading : "くりかえしひとつぶ"},
	{id : 858, name : "ピエロ", credit : "KEI feat. 初音ミク", reading : "ぴえろ"},
	{id : 65, name : "徒花ネクロマンシー", credit : "フランシュシュ", reading : "あだばなねくろまんしー"},
	{id : 1161, name : "リニアブルーを聴きながら", credit : "UNISON SQUARE GARDEN", reading : "りにあぶるーをききながら"},
	{id : 731, name : "渚にまつわるエトセトラ", credit : "PUFFY", reading : "なぎさにまつわるえとせとら"},
	{id : 793, name : "初恋", credit : "村下孝蔵", reading : "はつこい"},
	{id : 574, name : "セーラー服と機関銃", credit : "薬師丸ひろ子", reading : "せーらーふくときかんじゅう"},
	{id : 732, name : "なごり雪", credit : "かぐや姫", reading : "なごりゆき"},
	{id : 202, name : "贈る言葉", credit : "海援隊", reading : "おくることば"},
	{id : 1130, name : "Lovers again", credit : "Exile", reading : "らヴぁーずあげいん"},
	{id : 782, name : "白日", credit : "King Gnu", reading : "はくじつ"},
	{id : 143, name : "Wish", credit : "嵐", reading : "ういっしゅ"},
	{id : 227, name : "Orion", credit : "中島美嘉", reading : "おりおん"},
	{id : 1081, name : "you ", credit : "倖田來未", reading : "ゆー"},
	{id : 954, name : "Heavenly days", credit : "新垣結衣", reading : "へぶんりーでいず"},
	{id : 1123, name : "4'33\"", credit : "John Cage", reading : "よんぷんさんじゅうさんびょう 4分33秒"},
	{id : 113, name : "1925", credit : "冨田悠斗(とみー/T-POCKET) feat. 初音ミク", reading : "いちきゅうにーごー"},
	{id : 1141, name : "Love Destiny", credit : "堀江由衣", reading : "らぶですてぃにー"},
	{id : 874, name : "「ひとりで生きられそう」って それってねえ、褒めているの？", credit : "Juice=Juice", reading : "ひとりでいきられそうってそれってねえほめているの"},
	{id : 190, name : "えれくとりっく・えんじぇう", credit : "ヤスオ feat. 初音ミク", reading : "えれくとりっくえんじぇぅ"},
	{id : 758, name : "Never Grow Up", credit : "ちゃんみな", reading : "ねヴぁーぐろーあっぷ"},
	{id : 659, name : "強く儚い者たち", credit : "Cocco", reading : "つよくはかないものたち"},
	{id : 1128, name : "Lovers", credit : "Sumika", reading : "らヴぁーず "},
	{id : 467, name : "Gee", credit : "少女時代", reading : "じー"},
	{id : 58, name : "明日も", credit : "SHISHAMO", reading : "あしたも"},
	{id : 554, name : "ずっと好きだった", credit : "斉藤和義", reading : "ずっとすきだった"},
	{id : 148, name : "WOW WAR TONIGHT ～時には起こせよムーヴメント～", credit : "H Jungle with t", reading : "うぉううぉーとぅないとときにはおこせよむーヴめんと"},
	{id : 1142, name : "LOVEドッきゅん♥", credit : "Club Prince", reading : "らぶどっきゅん"},
	{id : 520, name : "シングルベッド", credit : "シャ乱Q", reading : "しんぐるべっど"},
	{id : 493, name : "15の夜", credit : "尾崎豊", reading : "じゅうごのよる"},
	{id : 17, name : "会いたかった", credit : "AKB48", reading : "あいたかった"},
	{id : 1220, name : "One Night Carnival", credit : "氣志團", reading : "わんないとかーにばる"},
	{id : 649, name : "CHA-LA HEAD-CHA-LA", credit : "影山ヒロノブ", reading : "ちゃらへっどしゃら"},
	{id : 164, name : "エアーマンが倒せない", credit : "Team.ねこかん【猫】", reading : "えあーまんがたおせない"},
	{id : 601, name : "宙船(そらふね)", credit : "TOKIO", reading : "そらふね"},
	{id : 1089, name : "友情物語", credit : "Aice5", reading : "ゆうじょうものがたり"},
	{id : 917, name : "冬がはじまるよ", credit : "槇原敬之", reading : "ふゆははじまるよ"},
	{id : 488, name : "車輪の唄", credit : "BUMP OF CHICKEN", reading : "しゃりんのうた"},
	{id : 177, name : "エゴロック", credit : "すりぃ", reading : "えごろっく"},
	{id : 66, name : "adrenaline!!!", credit : "TrySail", reading : "あどれなりん"},
	{id : 724, name : "どんなときも。", credit : "槇原敬之", reading : "どんなときも"},
	{id : 1199, name : "Romanticが止まらない", credit : "C-C-B", reading : "ろまんてぃっくがとまらない"},
	{id : 866, name : "Bittersweet", credit : "嵐", reading : "びたーすいーと"},
	{id : 870, name : "瞳をとじて", credit : "平井堅", reading : "ひとみをとじて"},
	{id : 1138, name : "LOVEずっきゅん", credit : "相対性理論", reading : "らぶずっきゅん"},
	{id : 948, name : "baby sweet berry love", credit : "小倉唯", reading : "べいびーすうぃーとべりーらぶ"},
	{id : 867, name : "ひだまりの詩", credit : "Le Couple", reading : "ひだまりのうた"},
	{id : 4, name : "​I'll be the one", credit : "HΛL", reading : "あいいうびーざわん"},
	{id : 594, name : "そこに空があるから", credit : "江崎とし子", reading : "そこにそらがあるから"},
	{id : 51, name : "Act! Addict! Actors!", credit : "A3ders!", reading : "あくとあでぃくとあくたーず"},
	{id : 474, name : "The Everlasting Guilty Crown", credit : "EGOIST", reading : "じえばーらんてぃんぐぎるてぃくらうん"},
	{id : 614, name : "ダイヤモンドハッピー", credit : "STAR☆ANIS", reading : "だいやもんどはっぴー"},
	{id : 1126, name : "Rising Hope", credit : "LiSA", reading : "らいじんぐほーぷ"},
	{id : 90, name : "歩いていこう!", credit : "東山奈央", reading : "あるいていこう"},
	{id : 978, name : "ぼなぺてぃーと♡S", credit : "ブレンド・A", reading : "ぼなぺてぃーとえす"},
	{id : 272, name : "カラフル", credit : "ClariS", reading : "からふる まどまぎ まどマギ"},
	{id : 1018, name : "回レ！雪月花", credit : "歌組雪月花", reading : "まわれゆきげっか"},
	{id : 646, name : "CHANGE THE WORLD", credit : "V6", reading : "ちぇんじざわーるど"},
	{id : 353, name : "クリスマスソング", credit : "back number", reading : "くりすますそんぐ"},
	{id : 162, name : "ウンディーネ", credit : "牧野由依", reading : "うんでぃーね"},
	{id : 1171, name : "ルピナスの子守歌", credit : "MAHO堂", reading : "るぴなすのこもりうた"},
	{id : 1078, name : "やさしさの種子", credit : "大道寺知世(岩男潤子)&友枝小学校コーラス部", reading : "やさしさのたね"},
	{id : 423, name : "最後の雨", credit : "中西保志", reading : "さいごのあめ"},
	{id : 343, name : "Good-bye Days", credit : "YUI", reading : "ぐっばいでいず"},
	{id : 465, name : "幸せ", credit : "Back number", reading : "しあわせ"},
	{id : 1048, name : "メトロノーム", credit : "米津玄師", reading : "めとろのーむ"},
	{id : 1072, name : "約束", credit : "如月千早(今井麻美)", reading : "やくそく"},
	{id : 1042, name : "make you happy", credit : "NiziU", reading : "めいくゆーはっぴー"},
	{id : 542, name : "好き!雪!本気マジック", credit : "Mitchie M feat. 初音ミク", reading : "すきゆきほんきまじっく"},
	{id : 1000, name : "マジLOVE1000%", credit : "ST☆RISH", reading : "まじらぶせんぱーせんと"},
	{id : 880, name : "ヒプノシスマイク -Division Rap Battle-", credit : "Division All Stars", reading : "ひぷのしすまいくでぃびじょんらっぷばとる"},
	{id : 900, name : "Fancy Baby Doll", credit : "田村ゆかり", reading : "ふぁんしーべいびーどーる"},
	{id : 944, name : "ふわふわ♪", credit : "牧野由依", reading : "ふわふわ"},
	{id : 155, name : "うっせえわ", credit : "Ado", reading : "うっせぇわ"},
	{id : 127, name : "if...", credit : "DA PUMP", reading : "いふ"},
	{id : 112, name : "以心電信", credit : "ORANGE RANGE", reading : "いしんでんしん"},
	{id : 166, name : "栄光の架橋", credit : "ゆず", reading : "えいこうのかけはし"},
	{id : 173, name : "YELL", credit : "いきものがかり", reading : "えーる"},
	{id : 1106, name : "ゆりゆららららゆるゆり大事件", credit : "七森中☆ごらく部", reading : "ゆりゆららららゆるゆりだいじけん"},
	{id : 538, name : "スカイクラッドの観測者", credit : "いとうかなこ", reading : "すかいくらっどのかんそくしゃ"},
	{id : 957, name : "冒険でしょでしょ?", credit : "平野綾", reading : "ぼうけんでしょでしょ"},
	{id : 1205, name : "ワイワイワールド", credit : "水森亜土", reading : "わいわいわーるど"},
	{id : 15, name : "Aitai", credit : "加藤ミリヤ", reading : "あいたい"},
	{id : 797, name : "ハッピーエンド", credit : "back number", reading : "はっぴーえんど"},
	{id : 418, name : "壊れかけのRadio", credit : "德永英明", reading : "こわれかけのれでぃお"},
	{id : 267, name : "神っぽいな", credit : "ピノキオピー feat. 初音ミク", reading : "かみっぽいな"},
	{id : 908, name : "フォニイ", credit : "ツミキ feat. 可不", reading : "ふぉにい phony"},
	{id : 510, name : "GIRAFFE BLUES", credit : "ワルキューレ", reading : "じらふぶるーず"},
	{id : 40, name : "青いベンチ", credit : "サスケ", reading : "あおいべんち"},
	{id : 894, name : "ヒロイン", credit : "back number", reading : "ひろいん"},
	{id : 1103, name : "夢見る少女じゃいられない", credit : "相川七瀬", reading : "ゆめみるしょうじょじゃいられない"},
	{id : 425, name : "Silent night", credit : "Franz Xaver Gruber", reading : "さいれんとないと"},
	{id : 140, name : "We Wish You a Merry Christmas", credit : "Arthur Warrell", reading : "うぃーうぃっしゅゆーあめりーくりすます"},
	{id : 185, name : "ebb and flow", credit : "Ray", reading : "えぶあんどふろう"},
	{id : 352, name : "クリスマス・イブ", credit : "山下達郎", reading : "くりすますいぶ"},
	{id : 389, name : "恋人がサンタクロース", credit : "松任谷由実", reading : "こいびとがさんたくろーす"},
	{id : 648, name : "チキンライス", credit : "浜田雅功,槇原敬之", reading : "ちきんらいす"},
	{id : 992, name : "Magia", credit : "Kalafina", reading : "まぎあ まどまぎ まどマギ"},
	{id : 1017, name : "丸ノ内サディスティック", credit : "椎名林檎", reading : "まるのうちさでぃすてぃっく"},
	{id : 227, name : "ORION", credit : "中島美嘉", reading : "おりおん"},
	{id : 1172, name : "ルミナス", credit : "ClariS", reading : "るみなす まどまぎ まどマギ"},
	{id : 1207, name : "勿忘", credit : "Awesome City Club", reading : "わすれな"},
	{id : 951, name : "ベテルギウス", credit : "優里", reading : "べてるぎうす"},
	{id : 900, name : "Fancy baby doll", credit : "田村ゆかり", reading : "ふぁんしーべいびーどーる"},
	{id : 130, name : "今好きになる。", credit : "HoneyWorks feat. 初音ミク", reading : "いますきになる"},
	{id : 1070, name : "桃ノ花ビラ", credit : "大塚愛", reading : "もものはなびら"},
	{id : 333, name : "キラメキラリ", credit : "高槻やよい(CV: 仁後真耶子)", reading : "きらめきらり"},
	{id : 59, name : "阿修羅ちゃん", credit : "Ado", reading : "あしゅらちゃん"},
	{id : 1121, name : "ヨワネハキ", credit : "MAISONdes feat. 和ぬか, asmi", reading : "よわねはき"},
	{id : 1016, name : "マリオネットの心", credit : "星井美希(長谷川明子)", reading : "まりおねっとのこころ"},
	{id : 525, name : "シンデレラ", credit : "DECO*27 feat. 初音ミク", reading : "しんでれら"},
	{id : 1175, name : "ルンに花咲く恋もある", credit : "ワルキューレ", reading : "るんにはなさくこいもある"},
	{id : 998, name : "MajiでKoiする5秒前", credit : "広末涼子", reading : "まじでこいするごびょうまえ"},
	{id : 472, name : "SHAKE", credit : "SMAP", reading : "しぇいく"},
	{id : 968, name : "僕らは今のなかで", credit : "μ's", reading : "ぼくらはいまのなかで"},
	{id : 1047, name : "めてお☆いんぱくと", credit : "田村ゆかり", reading : "めておいんぱくと"},
	{id : 681, name : "天体観測", credit : "BUMP OF CHICKEN", reading : "てんたいかんそく"},
	{id : 676, name : "テレキャスタービーボーイ", credit : "すりぃ feat. 鏡音レン", reading : "てれきゃすたーびーぼーい"},
	{id : 517, name : "silky heart", credit : "堀江由衣", reading : "しるきーはーと"},
	{id : 191, name : "エンヴィーベイビー", credit : "Kanaria feat. GUMI", reading : "えんヴぃーべいびー"},
	{id : 86, name : "Alive a Life", credit : "松本梨香", reading : "あらいぶあらいふ"},
	{id : 485, name : "Justiφ's", credit : "ISSA", reading : "じゃすてぃふぁいず"},
	{id : 158, name : "ウラオモテ・フォーチュン", credit : "佐倉千代(CV: 小澤亜李)", reading : "うらおもてふぉーちゅん"},
	{id : 606, name : "ダーリンダンス", credit : "かいりきベア feat. 初音ミク", reading : "だーりんだんす"},
	{id : 38, name : "愛をとりもどせ!!", credit : "クリスタルキング", reading : "あいをとりもどせ"},
	{id : 239, name : "Cagayake!GIRLS", credit : "放課後ティータイム", reading : "かがやけがーるず"},
	{id : 397, name : "GO! GO! MANIAC", credit : "放課後ティータイム", reading : "ごーごーまにあっく"},
	{id : 909, name : "深い森", credit : "Do As Infinity", reading : "ふかいもり"},
	{id : 530, name : "スイートマジック", credit : "Junky feat. 鏡音リン", reading : "すいーとまじっく"},
	{id : 801, name : "ハッピーシンセサイザ", credit : "Easy Pop feat. 巡音ルカ GUMI", reading : "はっぴーしんせさいざ"},
	{id : 159, name : "裏表ラバーズ", credit : "wowaka feat. 初音ミク", reading : "うらおもてらばーず"},
	{id : 245, name : "カゲロウデイズ", credit : "じん feat. 初音ミク", reading : "かげろうでいず"},
	{id : 273, name : "Calc.", credit : "ジミーサムP feat. 初音ミク", reading : "かるく"},
	{id : 81, name : "天ノ弱", credit : "164 feat.GUMI", reading : "あまのじゃく"},
	{id : 342, name : "グッバイ宣言", credit : "Chinozo feat. FloweR", reading : "ぐっばいせんげん"},
	{id : 709, name : "とまどい→レシピ", credit : "みかくにんぐッ！", reading : "とまどいれしぴ"},
	{id : 1159, name : "リカバーデコレーション", credit : "小野寺小咲(花澤香菜)", reading : "りかばりーでこれーしょん"},
	{id : 695, name : "童話迷宮", credit : "田村ゆかり", reading : "どうわめいきゅう"},
	{id : 863, name : "緋色の空", credit : "川田まみ", reading : "ひしょくのそら"},
	{id : 536, name : "Super Driver", credit : "平野綾", reading : "すーぱーどらいばー"},
	{id : 900, name : "fancy baby doll", credit : "田村ゆかり", reading : "ふぁんしーべいびーどーる"},
	{id : 287, name : "KissHug", credit : "aiko", reading : "きすはっぐ"},
	{id : 133, name : "インパーフェクト", credit : "オーイシマサヨシ", reading : "いんぱーふぇくと"},
	{id : 1192, name : "炉心融解", credit : "iroha feat. 鏡音リン", reading : "ろしんゆうかい"},
	{id : 222, name : "おはようイケブクロ", credit : "Buster Bros!!!", reading : "おはよういけぶくろ"},
	{id : 937, name : "プレイバック part 2", credit : "山口百恵", reading : "ぷれいばっくぱーとつー"},
	{id : 358, name : "紅", credit : "X JAPAN", reading : "くれない"},
	{id : 597, name : "染まるよ", credit : "チャットモンチー", reading : "そまるよ"},
	{id : 34, name : "irony", credit : "ClariS", reading : "あいろに "},
	{id : 259, name : "勝手にシンドバッド", credit : "サザンオールスターズ", reading : "かってにしんどばんど"},
	{id : 440, name : "錯覚CROSSROADS", credit : "BiBi", reading : "さっかくくろすろーず"},
	{id : 726, name : "小夜啼鳥恋詩", credit : "Printemps", reading : "ないちんげーるらぶそんぐ"},
	{id : 658, name : "TSUNAMI", credit : "サザンオールスターズ", reading : "つなみ"},
	{id : 836, name : "バリバリ最強No.1", credit : "FEEL SO BAD", reading : "ばりばりさいきょうなんばーわん"},
	{id : 962, name : "僕に彼女ができたんだ", credit : "SHISHAMO", reading : "ぼくにかのじょができたんだ"},
	{id : 29, name : "I LOVE...", credit : "Official髭男dism", reading : "あいらぶ"},
	{id : 949, name : "別の人の彼女になったよ", credit : "wacci", reading : "べつのひとのかのじょになったよ"},
	{id : 243, name : "かくれんぼ", credit : "優里", reading : "かくれんぼ"},
	{id : 69, name : "あなたに恋をしてみました", credit : "Chay", reading : "あなたにこいをしてみました"},
	{id : 254, name : "片想い", credit : "miwa", reading : "かたおもい"},
	{id : 16, name : "会いたいよ", credit : "手塚翔太", reading : "あいたいよ"},
	{id : 571, name : "制服のマネキン", credit : "乃木坂46", reading : "せいふくのまねきん"},
	{id : 853, name : "パンダヒーロー", credit : "ハチ feat. GUMI", reading : "ぱんだひーろー"},
	{id : 1204, name : "WILD EYES", credit : "水樹奈々", reading : "わいるどあいず"},
	{id : 1001, name : "マジLOVE2000%", credit : "ST☆RISH", reading : "まじらぶにせんぱーせんと"},
	{id : 1038, name : "ムズイ", credit : "22/7(ナナニジ)", reading : "むずい"},
	{id : 895, name : "First Step", credit : "長瀬麻奈(神田沙也加)", reading : "ふぁーすとすてっぷ"},
	{id : 491, name : "SHINING LINE*", credit : "STAR☆ANIS", reading : "しゃんにんぐらいん"},
	{id : 612, name : "Time after time ～花舞う街で～", credit : "倉木麻衣", reading : "たいむあふたーたいむはなまうまちで"},
	{id : 763, name : "願い事ひとつだけ", credit : "小松未歩", reading : "ねがいことひとつだけ"},
	{id : 1182, name : "LEVEL5-judgelight-", credit : "fripSide", reading : "れべるふぁいぶじゃっじらいと"},
	{id : 983, name : "why,or why not", credit : "片霧烈火", reading : "ほわいおあほわいのっと わいおあわいのっと"},
	{id : 637, name : "Dang Dang 気になる", credit : "中村由真", reading : "だんだんきになる"},
	{id : 849, name : "バレンタイン・キッス", credit : "国生さゆり", reading : "ばれんたいんきっす"},
	{id : 456, name : "残響散歌", credit : "Aimer", reading : "ざんきょうさんか"},
	{id : 1097, name : "Ubiquitous dB", credit : "ユナ(神田沙也加)", reading : "ゆびきたすでじべる"},
	{id : 218, name : "おねがいダーリン", credit : "ナナホシ管弦楽団 feat. ONE", reading : "おねがいだーりん"},
	{id : 1057, name : "Melody in the Dark", credit : "UNDEAD", reading : "めろでぃーいんざだーく"},
	{id : 129, name : "イマジネーション", credit : "SPYAIR", reading : "いまじねーしょん"},
	{id : 197, name : "oath sign", credit : "LiSA", reading : "おーすさいん"},
	{id : 1065, name : "motto☆派手にね！", credit : "戸松遥", reading : "もっとはでにね"},
	{id : 504, name : "JOINT", credit : "川田まみ", reading : "じょいんと"},
	{id : 55, name : "朝と夜の物語", credit : "Sound Horizon", reading : "あさとよるのものがたり"},
	{id : 1148, name : "LOVE YOU ONLY", credit : "TOKIO", reading : "らぶゆーおんりー"},
	{id : 761, name : "ね〜え?", credit : "松浦亜弥", reading : "ねーえ"},
	{id : 668, name : "Departures ～あなたにおくるアイの歌～", credit : "EGOIST", reading : "でぃぱーちゃーずあなたにおくるあいのうた"},
	{id : 967, name : "僕らのLIVE 君とのLIFE", credit : "μ's", reading : "ぼくらのらいぶきみとのらいぶ"},
	{id : 934, name : "ぶる～べりぃ とれいん", credit : "南ことり(内田彩)", reading : "ぶるーべりぃとれいん"},
	{id : 1135, name : "Love wing bell", credit : "μ's", reading : "らぶうぃんぐべる"},
	{id : 684, name : "Do As Infinity", credit : "深い森", reading : "どぅーえすいんふぃにてぃ"},
	{id : 661, name : "Dearest", credit : "浜崎あゆみ", reading : "でぃあれすと"},
	{id : 527, name : "侵略ノススメ☆", credit : "ULTRA-PRISM with イカ娘（金元寿子）", reading : "しんりゃくのすすめ"},
	{id : 686, name : "東京サマーセッション", credit : "HoneyWorks feat. CHiCO", reading : "とうきょうさまーせっしょん"},
	{id : 706, name : "届かない恋", credit : "上原れな", reading : "とどかないこい"},
	{id : 31, name : "アイリス", credit : "藍井エイル", reading : "あいりす"},
	{id : 124, name : "INNOCENCE", credit : "藍井エイル", reading : "いのせんす"},
	{id : 109, name : "IGNITE", credit : "藍井エイル", reading : "いぐないと"},
	{id : 125, name : "innocent starter", credit : "水樹奈々", reading : "いのせんとすたーたー"},
	{id : 903, name : "PHANTOM MINDS", credit : "水樹奈々", reading : "ふぁんとむまいんず"},
	{id : 455, name : "3月9日", credit : "レミオロメン", reading : "さんがつここのか"},
	{id : 970, name : "星屑ビーナス", credit : "Aimer", reading : "ほしくずびーなす"},
	{id : 215, name : "オドループ", credit : "フレデリック", reading : "おどるーぷ"},
	{id : 102, name : "いいから", credit : "WANIMA", reading : "いいから"},
	{id : 436, name : "サクラハッピーイノベーション", credit : "森園立夏,芳乃シャルル,葛木姫乃,瑠川さら,陽ノ下葵", reading : "さくらはっぴーいのべーしょん"},
	{id : 815, name : "ハナノイロ", credit : "nano.RIPE", reading : "はなのいろ"},
	{id : 776, name : "呪いは水色", credit : "大森靖子", reading : "のろいはみずいろ"},
	{id : 1026, name : "みっくしゅじゅーちゅ", credit : "大森靖子", reading : "みっくしゅじゅーちゅ"},
	{id : 328, name : "きゅるきゅる", credit : "大森靖子", reading : "きゅるきゅる"},
	{id : 755, name : "二番目のピンク", credit : "さめざめ", reading : "にばんめのぴんく"},
	{id : 774, name : "ノスタルジックJ-pop", credit : "大森靖子", reading : "のすたるじっくじぇーぽっぷ"},
	{id : 411, name : "子供じゃないもん17", credit : "大森靖子", reading : "こどもじゃないもんせぶんてぃーん"},
	{id : 580, name : "絶対彼女", credit : "大森靖子", reading : "ぜったいかのじょ"},
	{id : 391, name : "恋人みたいに。", credit : "さめざめ", reading : "こいびとみたいに"},
	{id : 480, name : "死神", credit : "大森靖子", reading : "しにがみ"},
	{id : 997, name : "マジックミラー", credit : "大森靖子", reading : "まじっくみらー"},
	{id : 688, name : "TOKYO BLACK HOLE", credit : "大森靖子", reading : "とうきょうぶらっくほーる"},
	{id : 541, name : "好きな人がいること", credit : "知英", reading : "すきなひとがいること"},
	{id : 660, name : "Dear...", credit : "西野カナ", reading : "でぃあ"},
	{id : 1149, name : "Love You More", credit : "GENERATIONS from EXILE TRIBE", reading : "らぶゆーもあ"},
	{id : 1071, name : "モンスター", credit : "嵐", reading : "もんすたー"},
	{id : 260, name : "悲しみよこんにちは", credit : "斉藤由貴", reading : "かなしみよこんにちは"},
	{id : 433, name : "SAKURAスキップ", credit : "fourfolium", reading : "さくらすきっぷ"},
	{id : 284, name : "ギガンティックO.T.N", credit : "ギガP feat. 鏡音レン", reading : "ぎがんてぃっくおーてぃーえぬ"},
	{id : 262, name : "花瓶の花", credit : "石崎ひゅーい", reading : "かびんのはな"},
	{id : 585, name : "ゼロのままでいられたら", credit : "Official髭男dism", reading : "ぜろのままでいられたら"},
	{id : 752, name : "虹色の戦争", credit : "SEKAI NO OWARI", reading : "にじいろのせんそう"},
	{id : 1178, name : "レオ", credit : "優里", reading : "れお"},
	{id : 225, name : "面影ワープ", credit : "nano.RIPE", reading : "おもかげわーぷ"},
	{id : 298, name : "ギミー！レボリューション", credit : "内田真礼", reading : "ぎみーれぼりゅーしょん"},
	{id : 431, name : "逆夢", credit : "King Gnu", reading : "さかゆめ"},
	{id : 1218, name : "ワルキューレは裏切らない", credit : "ワルキューレ", reading : "わるきゅーれはうらぎらない"},
	{id : 374, name : "小悪魔だってかまわない！", credit : "めいちゃん", reading : "こあくまだってかまわない"},
	{id : 10, name : "愛燦燦", credit : "美空ひばり", reading : "あいさんさん"},
	{id : 149, name : "Walking with you", credit : "Novelbright", reading : "うぉーきんぐうぃずゆー"},
	{id : 453, name : "さらば碧き面影", credit : "ロードオブメジャー", reading : "さらばあおきおもかげ"},
	{id : 13, name : "アイス食べたいの歌", credit : "看谷にぃあ", reading : "あいすたべたいのうた あいちゅたべたいのうた"},
	{id : 348, name : "Climax Jump", credit : "AAA DEN-O form", reading : "くらいまっくすじゃんぷ"},
	{id : 627, name : "Double-Action", credit : "野上良太郎(佐藤健)＆モモタロス(関俊彦)", reading : "だぶるあくしょん"},
	{id : 784, name : "爆竜戦隊アバレンジャー", credit : "遠藤正明", reading : "ばくりゅうせんたいあばれんじゃー"},
	{id : 628, name : "WBX ～W-Boiled Extreme～", credit : "上木彩矢 w TAKUYA", reading : "だぶるびーえっくすだぶるぼいるどえくすとりーむ"},
	{id : 444, name : "侍戦隊シンケンジャー", credit : "サイキックラバー", reading : "さむらいせんたいしんけんじゃー"},
	{id : 492, name : "獣拳戦隊ゲキレンジャー", credit : "谷本貴義、ヤング・フレッシュ", reading : "じゅうけんせんたいげきれんじゃー"},
	{id : 835, name : "ハリケンジャー参上！", credit : "高取ヒデアキ", reading : "はりけんじゃーさんじょう"},
	{id : 184, name : "Anything Goes!", credit : "大黒摩季", reading : "えにしんぐごーず"},
	{id : 1012, name : "魔法戦隊マジレンジャー", credit : "岩崎貴文", reading : "まほうせんたいまじれんじゃー"},
	{id : 703, name : "特捜戦隊デカレンジャー", credit : "サイキックラバー", reading : "とくそうせんたいでかれんじゃー"},
	{id : 307, name : "君だけを守りたい", credit : "つるの剛士", reading : "きみだけをまもりたい"},
	{id : 161, name : "ウルトラマンコスモス~君にできるなにか", credit : "Project.DMM", reading : "うるとらまんこすもすきみにできるなにか"},
	{id : 535, name : "スーパー戦隊 ヒーローゲッター", credit : "Project.R", reading : "すーぱーせんたいひーろーげったー"},
	{id : 916, name : "冬がくれた予感", credit : "BiBi", reading : "ふゆがくれたよかん"},
	{id : 402, name : "告白日和、です！", credit : "南ことり(CV.内田 彩)＆小泉花陽(CV.久保ユリカ)", reading : "こくはくびよりです"},
	{id : 475, name : "地獄先生", credit : "相対性理論", reading : "じごくせんせい"},
	{id : 118, name : "いつの日も", credit : "阿部真央", reading : "いつのひも"},
	{id : 991, name : "Myra", credit : "Tani Yuuki", reading : "まいら"},
	{id : 424, name : "最終電車", credit : "パスピエ", reading : "さいしゅうでんしゃ"},
	{id : 1203, name : "ワールドワイドワンダー", credit : "TOKOTOKO (西沢さんP) feat. 初音ミク", reading : "わーるどわいどわんだー"},
	{id : 1154, name : "Rally Go Round", credit : "LiSA", reading : "らりーごーらうんど"},
	{id : 898, name : "ファミリーパーティー", credit : "きゃりーぱみゅぱみゅ", reading : "ふぁみりーぱーてぃー"},
	{id : 136, name : "IN MY DREAM", credit : "真行寺恵里", reading : "いんまいどりーむ"},
	{id : 672, name : "デビルマンのうた", credit : "十田敬三", reading : "でびるまんのうた"},
	{id : 415, name : "ごめんなさいのKissing You", credit : "E-girls", reading : "ごめんなさいのきっしんぐゆー"},
	{id : 406, name : "こころのたまご", credit : "Buono!", reading : "こころのたまご"},
	{id : 788, name : "Butterfly ", credit : "倖田來未", reading : "ばたふらい"},
	{id : 163, name : "え？あぁ、そう。", credit : "蝶々P feat.初音ミク", reading : "えあぁそう えああそう"},
	{id : 546, name : "ススメ→トゥモロウ", credit : "高坂穂乃果（新田恵海）、南ことり（内田彩）、園田海未（三森すずこ）", reading : "すすめとぅもろう"},
	{id : 547, name : "Star!!", credit : "CINDERELLA PROJECT", reading : "すたー"},
	{id : 122, name : "いとおしい人のために", credit : "佐藤朱美", reading : "いとおしい人のために"},
	{id : 558, name : "STYX HELIX", credit : "MYTH & ROID", reading : "すてゅくすへりっくす"},
	{id : 266, name : "竈門炭治郎のうた", credit : "椎名豪 feat. 中川奈美", reading : "かまどたんじろうのうた"},
	{id : 747, name : "涙のキッス", credit : "サザンオールスターズ", reading : "なみだのきっす"},
	{id : 268, name : "カメレオン", credit : "King Gnu", reading : "かめれおん"},
	{id : 872, name : "ヒトリジメ", credit : "グミ", reading : "ひとりじめ"},
	{id : 294, name : "Gift", credit : "坂本真綾", reading : "ぎふと"},
	{id : 39, name : "あ・え・い・う・え・お・あお!!", credit : "劇団ひととせ", reading : "あえいうえおあお"},
	{id : 832, name : "Paradise Lost", credit : "茅原実里", reading : "ぱらだいすろすと"},
	{id : 947, name : "Hazy", credit : "スフィア", reading : "へいじー"},
	{id : 653, name : "chocolate insomnia", credit : "羽川翼(堀江由衣)", reading : "ちょこれーといんそむにあ 物語シリーズ"},
	{id : 1094, name : "雪、無音、窓辺にて。", credit : "長門有希(茅原実里)", reading : "ゆきむおんまどべにて"},
	{id : 912, name : "舞台少女心得 幕間", credit : "愛城華恋(小山百代),星見純那(佐藤日向),露崎まひる(岩田陽葵),石動双葉(生田輝),花柳香子(伊藤彩沙),大場なな(小泉萌香),西條クロディーヌ(相羽あいな),天堂真矢(富田麻帆)", reading : "ぶたいしょうじょこころえまくあい"},
	{id : 512, name : "シリウス", credit : "藍井エイル", reading : "しりうす"},
	{id : 632, name : "Dancing in the Moonlight", credit : "ワルキューレ", reading : "だんしんぐいんざーむーんらいと"},
	{id : 479, name : "シドニア", credit : "angela", reading : "しどにあ"},
	{id : 936, name : "Pray ", credit : "水樹奈々", reading : "ぷれい "},
	{id : 521, name : "Synchrogazer", credit : "水樹奈々", reading : "しんくろげいざー"},
	{id : 460, name : "365日の紙飛行機", credit : "AKB48", reading : "さんびゃくろくじゅうごにちのかみひこうき"},
	{id : 905, name : "フィクション", credit : "sumika", reading : "ふぃくしょん"},
	{id : 514, name : "シリョクケンサ", credit : "40mP feat. GUMI", reading : "しりょくけんさ"},
	{id : 733, name : "謎", credit : "小松未歩", reading : "なぞ"},
	{id : 762, name : "ネオメロドラマティック", credit : "ポルノグラフィティ", reading : "ねおめろどらまてぃっく"},
	{id : 156, name : "初心LOVE", credit : "なにわ男子", reading : "うぶらぶ"},
	{id : 364, name : "群青日和", credit : "東京事変", reading : "ぐんじょうびより"},
	{id : 1116, name : "夜もすがら君想ふ", credit : "TOKOTOKO(西沢さんP) feat. GUMI", reading : "よもすがらきみおもう"},
	{id : 926, name : "Flamingo", credit : "米津玄師", reading : "ふらみんご"},
	{id : 1133, name : "Rusty Nail", credit : "X JAPAN", reading : "らすてぃねいる"},
	{id : 68, name : "あなたに会いたくて", credit : "DREAMS COME TRUE", reading : "あなたにあいたくて"},
	{id : 354, name : "CLICK", credit : "ClariS", reading : "くりっく"},
	{id : 1037, name : "夢幻クライマックス", credit : "℃-ute", reading : "むげんくらいまっくす"},
	{id : 217, name : "お願い！シンデレラ", credit : "CINDERELLA PROJECT", reading : "おねがいしんでれら"},
	{id : 1170, name : "ルパン三世のテーマ", credit : "ユー&エクスプロージョン・バンド", reading : "るぱんさんせいのてーま"},
	{id : 223, name : "思い出せなくなるその日まで", credit : "back number", reading : "おもいだせなくなるそのひまで"},
	{id : 626, name : "旅立ちの日に", credit : "redballoon + 小嶋登、坂本浩美、他", reading : "たびだちのひに"},
	{id : 808, name : "?でわっしょい", credit : "ゆの(阿澄佳奈), 宮子(水橋かおり), ヒロ(後藤邑子), 沙英(新谷良子)", reading : "はてなでわっしょい"},
	{id : 1191, name : "六兆年と一夜物語", credit : "kemu feat. IA", reading : "ろくちょうねんといちやものがたり"},
	{id : 729, name : "長い間", credit : "Kiroro", reading : "ながいあいだ"},
	{id : 640, name : "CheerS", credit : "ClariS", reading : "ちあーず"},
	{id : 401, name : "告白バンジージャンプ", credit : "halca", reading : "こくはくばんじーじゃんぷ"},
	{id : 434, name : "桜音", credit : "ピコ", reading : "さくらね"},
	{id : 1104, name : "ユメヲカケル!", credit : "スペシャルウィーク(和氣あず未),サイレンススズカ(高野麻里佳),トウカイテイオー(Machico),ウオッカ(大橋彩香),ダイワスカーレット(木村千咲),ゴールドシップ(上田 瞳),メジロマックイーン(大西沙織)", reading : "ゆめをかける"},
	{id : 562, name : "snowdrop", credit : "春奈るな", reading : "すのーどろっぷ 物語シリーズ"},
	{id : 775, name : "ノルニル", credit : "やくしまるえつこメトロオーケストラ", reading : "のるにる"},
	{id : 213, name : "乙女のルートはひとつじゃない!", credit : "angela", reading : "おとめのるーとはひとつじゃない"},
	{id : 131, name : "INVOKE", credit : "T.M.Revolution", reading : "いんヴぉーく インヴォーク"},
	{id : 315, name : "君はロックを聴かない", credit : "あいみょん", reading : "きみはろっくをきかない"},
	{id : 537, name : "Scarlet Ballet", credit : "May'n", reading : "すかーれっとばれえ"},
	{id : 181, name : "エデン", credit : "水樹奈々", reading : "えでん"},
	{id : 1087, name : "夕景イエスタデイ", credit : "じん（自然の敵P）feat. IA", reading : "ゆうけいいえすたでい"},
	{id : 381, name : "恋空予報", credit : "電ポルP feat. GUMI", reading : "こいぞらよほう"},
	{id : 22, name : "アイノカタチ", credit : "MISIA feat. HIDE(GReeeeN)", reading : "あいのかたち"},
	{id : 385, name : "恋のミクル伝説", credit : "朝比奈みくる(後藤邑子)", reading : "こいのみくるでんせつ"},
	{id : 137, name : "VALENTI", credit : "BoA", reading : "ヴぁれんち"},
	{id : 1014, name : "まもりたい 〜White Wishes〜", credit : "BoA", reading : "まもりたいほわいとうぃっしゅ"},
	{id : 669, name : "Depend on you", credit : "浜崎あゆみ", reading : "でぃぺんどおんゆー"},
	{id : 483, name : "SHINY DAYS", credit : "亜咲花", reading : "しゃいにーでいず"},
	{id : 743, name : "なにやってもうまくいかない", credit : "meiyo", reading : "なにやってもうまくいかない"},
	{id : 950, name : "ペッパー警部", credit : "ピンク・レディー", reading : "ぺっぱーけいぶ"},
	{id : 103, name : "いい日旅立ち", credit : "山口百恵", reading : "いいひたびだち"},
	{id : 677, name : "田園", credit : "玉置浩二", reading : "でんえん"},
	{id : 1176, name : "ray", credit : "BUMP OF CHICKEN", reading : "れい"},
	{id : 457, name : "三原色", credit : "YOASOBI", reading : "さんげんしょく"},
	{id : 989, name : "my sweet heart", credit : "小松里賀", reading : "まいすいーとはーと"},
	{id : 1155, name : "Realize!", credit : "i☆Ris", reading : "りあらいず realise"},
	{id : 641, name : "Cheers！デリシャスパーティ♡プリキュア", credit : "Machico", reading : "ちあーずでりしゃすぱーてぃぷりきゅあ"},
	{id : 766, name : "熱烈歓迎わんだーらんど", credit : "宮永咲(植田佳奈),原村和(小清水亜美),片岡優希(釘宮理恵),染谷まこ(白石涼子),竹井久(伊藤静)", reading : "ねつれつかんげいわんだーらんど"},
	{id : 573, name : "セーラースターソング", credit : "花沢加絵", reading : "せーらーすたーそんぐ"},
	{id : 716, name : "ドラマチックガール", credit : "わか・ふうり・ゆな from STAR☆ANIS、るか・もな・みき from AIKATSU☆STARS!", reading : "どらまちっくがーる"},
	{id : 533, name : "SUPER∞STREAM", credit : "篠ノ之箒(日笠陽子),セシリア・オルコット(ゆかな),凰鈴音(下田麻美),シャルル・デュノア(花澤香菜),ラウラ・ボーデヴィッヒ(井上麻里奈)", reading : "すーぱーすーぱーすとりーむ"},
	{id : 269, name : "COLORS", credit : "FLOW", reading : "からーず colours"},
	{id : 882, name : "秘密基地", credit : "高田梢枝", reading : "ひみつきち"},
	{id : 1027, name : "ミックスナッツ", credit : "Official髭男dism", reading : "みっくすなっつ"},
	{id : 1011, name : "魔法少女とチョコレゐト", credit : "ピノキオピー feat. 初音ミク", reading : "まほうしょうじょとちょこれーと まほうしょうじょとちょこれゐと"},
	{id : 165, name : "永遠のあくる日", credit : "Ado", reading : "えいえんのあくるひ"},
	{id : 1112, name : "欲望に満ちた青年団", credit : "ONE OK ROCK", reading : "よくぼうにみちたせいねんだん"},
	{id : 1140, name : "LOVE SONG", credit : "三代目 J Soul Brothers from EXILE TRIBE", reading : "らぶそんぐ"},
	{id : 553, name : "STAND-ALONE", credit : "Aimer", reading : "すたんどあろん"},
	{id : 305, name : "君が好き", credit : "清水翔太", reading : "きみがすき"},
	{id : 390, name : "恋人ごっこ", credit : "マカロニえんぴつ", reading : "こいびとごっこ"},
	{id : 820, name : "花火", credit : "三代目 J Soul Brothers from EXILE TRIBE", reading : "はなび"},
	{id : 47, name : "アカシア", credit : "BUMP OF CHICKEN", reading : "あかしあ"},
	{id : 439, name : "叫べ", credit : "angela", reading : "さけべ"},
	{id : 337, name : "禁断のレジスタンス", credit : "水樹奈々", reading : "きんだんのれじすたんす"},
	{id : 506, name : "少女レイ", credit : "みきとP feat. 初音ミク", reading : "しょうじょれい"},
	{id : 803, name : "Happy Birthday to You", credit : "Patty Hill, Mildred J. Hill", reading : "はっぴーばーすでいーとぅゆー"},
	{id : 332, name : "キラメキ", credit : "wacci", reading : "きらめき"},
	{id : 746, name : "涙のイエスタデー", credit : "GARNET CROW", reading : "なみだのいえすたでー"},
	{id : 204, name : "おしえて A to Z", credit : "田村ゆかり", reading : "おしえてえーとぅーずぃー おしえてatoz おしえて atoz"},
	{id : 377, name : "恋音と雨空", credit : "AAA", reading : "こいおととあまぞら"},
	{id : 1144, name : "Love Forever", credit : "加藤ミリヤ×清水翔太", reading : "らぶふぉーえばー"},
	{id : 1196, name : "ロボキッス", credit : "W", reading : "ろぼきっす"},
	{id : 1157, name : "リアルワールド", credit : "nano.RIPE", reading : "りあるわーるど"},
	{id : 663, name : "DESIRE -情熱-", credit : "中森明菜", reading : "でぃざいあじょうねつ"},
	{id : 1162, name : "流星", credit : "藍井エイル", reading : "りゅうせい"},
	{id : 46, name : "赤い涙", credit : "川田まみ", reading : "あかいなみだ"},
	{id : 169, name : "エヴリデイドリーム", credit : "佐久間まゆ(CV牧野由依)", reading : "えヴりでいどりーむ"},
	{id : 1136, name : "LOVE GAME", credit : "AIKATSU☆STARS", reading : "らぶげーむ"},
	{id : 188, name : "エブリデイワールド", credit : "雪ノ下雪乃(早見沙織)&由比ヶ浜結衣(東山奈央)", reading : "えぶりでいわーるど"},
	{id : 1092, name : "ユキトキ", credit : "やなぎなぎ", reading : "ゆきとき"},
	{id : 1005, name : "まちぶせ", credit : "石川ひとみ", reading : "まちぶせ"},
	{id : 1143, name : "LOVE涙色", credit : "松浦亜弥", reading : "らぶなみだいろ"},
	{id : 251, name : "風は予告なく吹く", credit : "ワルキューレ", reading : "かぜはよこくなくふく"},
	{id : 1217, name : "ワルキューレはあきらめない", credit : "ワルキューレ", reading : "わるきゅーれはあきらめない"},
	{id : 422, name : "最強ツインテール", credit : "AKB48", reading : "さいきょうついんてーる"},
	{id : 1202, name : "ワールドイズマイン", credit : "ryo feat. 初音ミク", reading : "わーるどいずまいん"},
	{id : 534, name : "スーパースターになったら", credit : "back number", reading : "すーぱーすたーになったら"},
	{id : 1021, name : "みかんハート", credit : "C&K", reading : "みかんはーと"},
	{id : 812, name : "花束", credit : "back number", reading : "はなたば"},
	{id : 324, name : "CAN YOU CELEBRATE?", credit : "安室奈美恵", reading : "きゃんゆーせれぶれいと"},
	{id : 799, name : "ハッピーサマーウェディング", credit : "モーニング娘。", reading : "はっぴーさまーうぇでぃんぐ Happy Summer Wedding"},
	{id : 253, name : "家族になろうよ", credit : "福山雅治", reading : "かぞくになろうよ"},
	{id : 89, name : "ありがとう", credit : "いきものがかり", reading : "ありがとう"},
	{id : 76, name : "アパッショナート", credit : "水樹奈々", reading : "あぱっしょなーと"},
	{id : 985, name : "WHITE REFLECTION", credit : "TWO-MIX", reading : "ほわいとりふれくしょん"},
	{id : 883, name : "ひみつのアッコちゃん", credit : "岡田恭子", reading : "ひみつのあっこちゃん"},
	{id : 678, name : "天才ドロンボー", credit : "小原乃梨子,八奈見乗児,立壁和也", reading : "てんさいどろんぼー"},
	{id : 323, name : "キャンディ キャンディ", credit : "堀江美都子、ザ・チャープス", reading : "きゃんでぃきゃんでぃ"},
	{id : 257, name : "ガッチャマンの歌", credit : "串田アキラ", reading : "がっちゃまんのうた"},
	{id : 1109, name : "よあけのみち", credit : "大杉久美子、アントワープ・チルドレン・コーラス", reading : "よあけのみち"},
	{id : 172, name : "エースをねらえ!", credit : "大杉久美子", reading : "えーすをねらえ"},
	{id : 833, name : "薔薇は美しく散る", credit : "鈴木宏子", reading : "ばらはうつくしくちる"},
	{id : 334, name : "銀河鉄道999", credit : "ゴダイゴ", reading : "ぎんがてつどうすりーないん"},
	{id : 1002, name : "マジンガーZ", credit : "水木一郎", reading : "まじんがーぜっと"},
	{id : 72, name : "Anniversary", credit : "KinKi Kids", reading : "あにばーさりー"},
	{id : 104, name : "いいんですか?", credit : "RADWIMPS", reading : "いいんですか"},
	{id : 879, name : "ヒプノシスマイク -Division Battle Anthem-", credit : "Division All Stars", reading : "ひぷのしすまいくでぃびじょんばとりあんせむ"},
	{id : 559, name : "Stella", credit : "Fling Posse", reading : "すてら"},
	{id : 258, name : "GUTS!", credit : "嵐", reading : "がっつ"},
	{id : 373, name : "喧嘩上等", credit : "氣志團", reading : "けんかじょうとう"},
	{id : 690, name : "桃源郷エイリアン", credit : "serial TV drama", reading : "とうげんきょうえいりあん"},
	{id : 555, name : "Stairway Generation", credit : "Base Ball Bear", reading : "すてあうぇいじぇねれーしょん"},
	{id : 500, name : "修羅", credit : "DOES", reading : "しゅら"},
	{id : 783, name : "バクチ・ダンサー", credit : "DOES", reading : "ばくちだんさー"},
	{id : 98, name : "AMBITIOUS JAPAN!", credit : "TOKIO", reading : "あんびしゃすじゃぱん"},
	{id : 1151, name : "ラブレター ", credit : "YOASOBI", reading : "らぶれたー"},
	{id : 522, name : "新時代", credit : "Ado", reading : "しんじだい"},
	{id : 540, name : "好きすぎて会いたい", credit : "エイトMAN", reading : "すきすぎてあいたい"},
	{id : 1068, name : "木綿のハンカチーフ", credit : "太田裕美", reading : "もめんのはんかちーふ"},
	{id : 83, name : "雨のMelody", credit : "KinKi Kids", reading : "あめのめろでぃ"},
	{id : 893, name : "Believe  ", credit : "嵐", reading : "びりーぶ"},
	{id : 1118, name : "夜撫でるメノウ", credit : "Ayase feat. 初音ミク", reading : "よるなでるめのう"},
	{id : 400, name : "ゴールデンタイムラバー", credit : "スキマスイッチ", reading : "ごーるでんたいむらばー"},
	{id : 1034, name : "MOON SIGNAL", credit : "スフィア", reading : "むーんしぐなる"},
	{id : 43, name : "青と夏", credit : "Mrs. GREEN APPLE", reading : "あおとなつ"},
	{id : 105, name : "Yeah! めっちゃホリディ", credit : "松浦亜弥", reading : "いぇーいめっちゃほりでぃ"},
	{id : 74, name : "アニマル", credit : "DECO*27,Rockwell feat. 初音ミク", reading : "あにまる"},
	{id : 598, name : "空", credit : "音無小鳥 (滝田樹里)", reading : "そら 「空」"},
	{id : 856, name : "PEACH", credit : "大塚愛", reading : "ぴーち"},
	{id : 860, name : "ヒカリへ", credit : "ザ・ベイビースターズ", reading : "ひかりへ"},
	{id : 589, name : "全力☆Summer!", credit : "angela", reading : "ぜんりょくさまー"},
	{id : 407, name : "ココロのちず", credit : "BOYSTYLE", reading : "こころのちず"},
	{id : 494, name : "SHOOT!", credit : "RO-KYU-BU!", reading : "しゅーと"},
	{id : 748, name : "涙目爆発音", credit : "ワルキューレ", reading : "なみだめばくはつおん"},
	{id : 263, name : "カフェオーレのうた", credit : "きっかレン", reading : "かふぇおーれのうた"},
	{id : 466, name : "幸せな結末", credit : "大滝詠一", reading : "しあわせなけつまつ"},
	{id : 286, name : "KISSして", credit : "KOH+", reading : "きすして"},
	{id : 827, name : "Habit", credit : "SEKAI NO OWARI", reading : "はびっと"},
	{id : 53, name : "悪魔の子", credit : "ヒグチアイ", reading : "あくまのこ"},
	{id : 719, name : "鳥の詩", credit : "Lia", reading : "とりのうた"},
	{id : 1053, name : "メリーメリー", credit : "一億円P feat. 初音ミク", reading : "めりーめりー"},
	{id : 630, name : "だんご3兄弟", credit : "速水けんたろう・茂森あゆみ", reading : "だんごさんきょうだい"},
	{id : 1104, name : "ユメヲカケル！", credit : "スペシャルウィーク(和氣あず未),サイレンススズカ(高野麻里佳),トウカイテイオー(Machico),ウオッカ(大橋彩香),ダイワスカーレット(木村千咲),ゴールドシップ(上田 瞳),メジロマックイーン(大西沙織)", reading : "ゆめをかける"},
	{id : 632, name : "Dancing In The Moonlight", credit : "ワルキューレ", reading : "だんしんぐいんざーむーんらいと"},
	{id : 322, name : "キャットラビング", credit : "香椎モイミ feat. 可不", reading : "きゃっとらびんぐ"},
	{id : 1114, name : "夜空はなんでも知ってるの？", credit : "CYaRon!", reading : "よぞらはなんでもしってるの"},
	{id : 727, name : "ないない", credit : "ReoNa", reading : "ないない"},
	{id : 736, name : "夏影 -summer lights-", credit : "Lia", reading : "なつかげ"},
	{id : 939, name : "プレパレード", credit : "逢坂大河(釘宮理恵) 櫛枝実乃梨(堀江由衣) 川嶋亜美(喜多村英梨)", reading : "ぷれぱれーど"},
	{id : 631, name : "だんご大家族", credit : "麻枝准", reading : "だんごだいかぞく"},
	{id : 643, name : "小さなてのひら", credit : "Lia", reading : "ちいさなてのひら"},
	{id : 1188, name : "ロウワー", credit : "ぬゆり feat. v flower", reading : "ろうわー"},
	{id : 250, name : "風のゆくえ", credit : "Ado", reading : "かぜのゆくえ 風の行方"},
	{id : 1025, name : "ミス・パラレルワールド", credit : "相対性理論", reading : "みすぱられるわーるど"},
	{id : 280, name : "カワルミライ", credit : "ちょうちょ", reading : "かわるみらい"},
	{id : 988, name : "My will", credit : "Dream", reading : "まいうぃる"},
	{id : 168, name : "Every Heart-ミンナノキモチ-", credit : "BoA", reading : "えヴりぃはーとみんなのきもち"},
	{id : 449, name : "さよならアンドロメダ", credit : "渋谷凛(福原綾香),森久保乃々(高橋花林),大和亜季(村中知)", reading : "さよならあんどろめた"},
	{id : 477, name : "静かな夜に", credit : "ラクス・クライン(田中理恵)", reading : "しずかなよるに"},
	{id : 794, name : "初恋の絵本", credit : "HoneyWorks feat. GUMI", reading : "はつこいのえほん"},
	{id : 593, name : "SOUVENIR", credit : "BUMP OF CHICKEN", reading : "そーヴぁにあ"},
	{id : 335, name : "金魚花火", credit : "大塚 愛", reading : "きんぎょうはなび"},
	{id : 1213, name : "私は最強", credit : "Ado", reading : "わたしはさいきょう"},
	{id : 549, name : "START DASH SENSATION", credit : "AIKATSU☆STARS", reading : "すたーとだっしゅせんせーしょん"},
	{id : 1030, name : "未来はオンナのためにある", credit : "ワルキューレ", reading : "みらいはおんなのためにある"},
	{id : 1183, name : "lemon", credit : "米津玄師", reading : "れもん"},
	{id : 705, name : "Top of the World", credit : "Carpenters", reading : "とっぷおぶざーわーるど"},
	{id : 356, name : "Crazy Party Night 〜ぱんぷきんの逆襲〜", credit : "きゃりーぱみゅぱみゅ", reading : "くれいじーぱーてぃないとぱんぷきんのぎゃくしゅう"},
	{id : 823, name : "Honey", credit : "chihiro", reading : "はにー"},
	{id : 229, name : "オリビアを聴きながら", credit : "杏里", reading : "おりびあをききながら"},
	{id : 611, name : "Timing", credit : "BLACK BISCUITS", reading : "たいみんぐ タイミング~Timing~"},
	{id : 247, name : "飾りじゃないのよ涙は", credit : "中森明菜", reading : "かざりじゃないのよなみだは"},
	{id : 302, name : "君がいるだけで", credit : "米米CLUB", reading : "きみがいるだけで"},
	{id : 375, name : "恋 ", credit : "back number", reading : "こい"},
	{id : 1169, name : "ルカルカ★ナイトフィーバー", credit : "samfree feat. 巡音ルカ", reading : "るかるかないとふぃーばー"},
	{id : 694, name : "True My Heart", credit : "ave;new feat. 佐倉紗織", reading : "とぅるーまいはーと きしめん"},
	{id : 345, name : "組曲『ニコニコ動画』", credit : "多数", reading : "ぐみきょくにこにこどうが にこにこぐみきょく ニコニコ組曲"},
	{id : 14, name : "I SAY YES", credit : "ICHIKO", reading : "あいせいいえす"},
	{id : 32, name : "アイロニ ", credit : "すこっぷ feat. 初音ミク", reading : "あいろに"},
	{id : 219, name : "お願いマッスル", credit : "紗倉ひびき（ファイルーズあい）、街雄鳴造（石川界人）", reading : "おねがいまっする"},
	{id : 447, name : "左右盲", credit : "ヨルシカ", reading : "さゆうもう"},
	{id : 85, name : "ALIVE", credit : "ClariS", reading : "あらいぶ"},
	{id : 459, name : "サンサンたいそう", credit : "ドリーミング", reading : "さんさんたいそう"},
	{id : 785, name : "ハジメテノオト", credit : "malo feat. 初音ミク", reading : "はじめてのおと"},
	{id : 993, name : "magnet", credit : "minato(流星P) feat. 初音ミク, 巡音ルカ", reading : "まぐねっと"},
	{id : 152, name : "詠人", credit : "北島三郎", reading : "うたびと"},
	{id : 1098, name : "ゆめいっぱい", credit : "関ゆみ子", reading : "ゆめいっぱい"},
	{id : 657, name : "月灯りふんわり落ちてくる夜", credit : "小川七生", reading : "つきあかりふんわりおちてくるよる"},
	{id : 296, name : "気まぐれメルシィ", credit : "八王子P feat. 初音ミク", reading : "きまぐれめるしぃ"},
	{id : 1200, name : "ロミオとシンデレラ", credit : "doriko feat. 初音ミク", reading : "ろみおとしんでれら"},
	{id : 753, name : "二息歩行", credit : "DECO*27 feat. 初音ミク", reading : "にそくほこう"},
	{id : 207, name : "おちゃめ機能", credit : "ゴジマジP feat. 重音テト", reading : "おちゃめきのう"},
	{id : 321, name : "キャットフード", credit : "doriko feat. 初音ミク", reading : "きゃっとふーど"},
	{id : 710, name : "ドミノ倒シ", credit : "すこっぷ feat. 初音ミク", reading : "どみのたおし"},
	{id : 539, name : "スキキライ", credit : "HoneyWorks feat. 鏡音リン,鏡音レン", reading : "すききらい"},
	{id : 486, name : "Just Be Friends", credit : "Dixie Flatline feat. 巡音ルカ", reading : "じゃすと びー ふれんず じゃうびふれんず"},
	{id : 52, name : "悪ノ召使", credit : "mothy(悪ノP) feat. 鏡音レン", reading : "あくのめしつかい"},
	{id : 28, name : "City Hunter〜愛よ消えないで〜", credit : "小比類巻かほる", reading : "あいよきえないで"},
	{id : 498, name : "祝福", credit : "YOASOBI", reading : "しゅくふく"},
	{id : 577, name : "世界のつづき", credit : "Ado", reading : "せかいのつづき"},
	{id : 308, name : "君と夏フェス", credit : "SHISHAMO", reading : "きみとなつふぇす"},
	{id : 932, name : "BLUE BIRD", credit : "浜崎あゆみ", reading : "ぶるーばーど"},
	{id : 600, name : "空の青さを知る人よ", credit : "あいみょん", reading : "そらのあおさをしるひとよ"},
	{id : 171, name : "ええじゃないか", credit : "ジャニーズWEST", reading : "ええじゃないか"},
	{id : 57, name : "明日があるさ", credit : "坂本九", reading : "あしたがあるさ"},
	{id : 635, name : "DANCE! おジャ魔女", credit : "MAHO堂", reading : "だんすおじゃまじょ"},
	{id : 619, name : "たからもの", credit : "こむろゆい", reading : "たからもの"},
	{id : 961, name : "僕たちが恋をする理由", credit : "坂本真綾", reading : "ぼくたちがこいをするりゆう"},
	{id : 71, name : "あなたのキスを数えましょう～You were mine～", credit : "小柳ゆき", reading : "あなたのきすをかぞえましょうゆーわーまいん"},
	{id : 179, name : "ETERNAL WIND〜ほほえみは光る風の中〜", credit : "森口博子", reading : "えたーなるうぃんどほほえみはひかるかぜのなか"},
	{id : 405, name : "ココロオドル", credit : "nobodyknows+", reading : "こころおどる"},
	{id : 291, name : "KICK BACK", credit : "米津玄師", reading : "きっくばっく"},
	{id : 60, name : "アスノヨゾラ哨戒班", credit : "Orangestar feat. IA", reading : "あすのよぞらしょうかいはん"},
	{id : 990, name : "my dearest", credit : "supercell", reading : "まいでぃあれすと"},
	{id : 974, name : "蛍の光", credit : "Robert Burns, 稲垣千頴", reading : "ほたるのひかり"},
	{id : 177, name : "エゴロック", credit : "すりぃ", reading : "えごろっく"},
	{id : 1211, name : "私たちになりたくて", credit : "美少女戦士セーラームーン SuperS（藤谷美和子）", reading : "わたしたちになりたくて"},
	{id : 1083, name : "You & Me", credit : "田村ゆかり", reading : "ゆーあんどみー"},
	{id : 1126, name : "rising hope", credit : "LiSA", reading : "らいじんぐほーぷ"},
	{id : 428, name : "サウスポー", credit : "ピンク・レディー", reading : "さうすぽー"},
	{id : 199, name : "OVER SOUL", credit : "林原めぐみ", reading : "おーばーそーる"},
	{id : 604, name : "soldier game", credit : "西木野真姫(Pile),園田海未(三森すずこ)&絢瀬絵里(南條愛乃)", reading : "そるじゃーげーむ"},
	{id : 1111, name : "YOKAZE", credit : "変態紳士クラブ", reading : "よかぜ"},
	{id : 317, name : "逆光", credit : "Ado", reading : "ぎゃっこう"},
	{id : 35, name : "アイヲウタエ", credit : "春奈るな", reading : "あいをうたえ 物語シリーズ"},
	{id : 915, name : "BBoom BBoom", credit : "MOMOLAND", reading : "ぶむぶむ"},
	{id : 864, name : "美女と野獣", credit : "Angela Lansbury", reading : "びじょとやじゅう"},
	{id : 78, name : "A Whole New World", credit : "Brad Kane, Lea Salonga", reading : "あほーるにゅーわーるど"},
	{id : 11, name : "I See the Light", credit : "Mandy Moore, Zachary Levi", reading : "あいしーざーらいと 輝く未来"},
	{id : 914, name : "フタリボシ", credit : "40㍍P feat. 初音ミク, GUMI", reading : "ふたりぼし"},
	{id : 1040, name : "迷宮バタフライ", credit : "ほしな歌唄(CV : 水樹奈々)", reading : "めいきゅうばたふらい"},
	{id : 167, name : "Euterpe", credit : "EGOIST", reading : "えうてるぺ エウテルペ"},
	{id : 1137, name : "ラブ・スコール", credit : "サンドラ・ホーン", reading : "らぶすこーる"},
	{id : 496, name : "sugar sweet nightmare", credit : "羽川翼（堀江由衣）", reading : "しゅがーすいーとないとめあ 物語シリーズ"},
];